overrides:
  - files:
      - '*.ts'
    parserOptions:
      project: './tsconfig.json'
    plugins:
      - "@angular-eslint"
    rules:
      '@angular-eslint/directive-selector':
        - error
        - { type: "attribute", prefix: "glyph", style: "camelCase" }
      '@angular-eslint/component-selector':
        - error
        - { type: "element", prefix: "glyph", style: "kebab-case" }
  - files:
    - '*.html'
    extends:
      - 'plugin:@angular-eslint/template/recommended'
