export const calendarEvents = {
    2021: [
        {
            date: '2021-01-01',
            events: [
                { localizedStartTime: '00:00', title: 'Demo1', description: 'Demo calendar event description' },
                { localizedStartTime: '00:00', title: 'Demo2', description: 'Demo calendar event description' },
            ],
        },
        {
            date: '2021-02-01',
            events: [
                { localizedStartTime: '00:00', title: 'Demo3', description: 'Demo calendar event description' },
                { localizedStartTime: '00:00', title: 'Demo4', description: 'Demo calendar event description' },
            ],
        },
    ],
    2020: [
        {
            date: '2020-01-01',
            events: [
                { localizedStartTime: '00:00', title: 'Demo1', description: 'Demo calendar event description' },
                { localizedStartTime: '00:00', title: 'Demo2', description: 'Demo calendar event description' },
            ],
        },
        {
            date: '2020-02-01',
            events: [
                { localizedStartTime: '00:00', title: 'Demo3', description: 'Demo calendar event description' },
                { localizedStartTime: '00:00', title: 'Demo4', description: 'Demo calendar event description' },
            ],
        },
    ],
};
export const themes = [
    { name: 'white', value: 'white', active: true },
    { name: 'dark', value: 'dark', active: false },
];
export const languages = [
    { name: 'english', value: 'en', active: true },
    { name: 'spanish', value: 'es', active: false },
];
export const appData = [
    {
        _id: '5ef1ba703ce37a53d7ca0e70',
        code: 'sales_old',
        status: '',
        name: 'Comercial',
        icon: 'local_offer',
        url: 'https://ecomdriv.axinocp1.central.inditex.grp/comercial',
        extranet_url: 'https://drive.inditex.com/comercial',
        roles: [ 'drive.comercial' ],
        deleted: false,
        created_at: '2020-06-23T08:16:48.234Z',
        updated_at: '2020-08-18T08:43:53.172Z',
        order: 1,
    },
    {
        _id: '5e6a75d1436a6147adff5148',
        code: 'sales',
        status: '',
        name: 'Comercial v2',
        icon: 'local_offer',
        url: 'https://drfrcomr-analytics-za.axinocp1.central.inditex.grp/drfrcomr/sales/home',
        extranet_url: 'https://drive.inditex.com/drfrcomr/sales/home',
        roles: [ 'Drive.Sales' ],
        deleted: false,
        created_at: '2020-03-12T17:48:01.978Z',
        updated_at: '2020-10-05T14:23:31.695Z',
        order: 2,
        parent: true,
        children: [
            {
                _id: '5e6a75d1436a6147adff5148',
                code: 'sales',
                status: '',
                name: 'Comercial',
                icon: 'home',
                url: 'https://drfrcomr-analytics-za.axinocp1.central.inditex.grp/drfrcomr/sales/home',
                extranet_url: 'https://drive.inditex.com/drfrcomr/sales/home',
                roles: [ 'Drive.Sales' ],
                deleted: false,
                created_at: '2020-03-12T17:48:01.978Z',
                updated_at: '2020-10-05T14:23:31.695Z',
                order: 17,
            },
            {
                _id: '5e6a73fa436a6176e6ff5147',
                code: 'physical_stores',
                status: '',
                name: 'Tiendas Físicas',
                icon: 'store',
                url: 'https://drfrpsts-analytics-za.axinocp1.central.inditex.grp/sales/physical-stores',
                extranet_url: 'https://drive.inditex.com/drfrpsts/sales/physical-stores',
                roles: [ 'Drive.Sales' ],
                deleted: false,
                created_at: '2020-03-12T17:40:10.477Z',
                updated_at: '2020-03-23T15:32:46.385Z',
                order: 18,
            },
            {
                _id: '5e6a7394436a615694ff5146',
                code: 'sint',
                status: '',
                name: 'Stock Integrado',
                icon: 'where_to_vote',
                url: 'https://drfrsint-analytics-za.axinocp1.central.inditex.grp/sales/integrated-stock',
                extranet_url: 'https://drive.inditex.com/drfrsint/sales/integrated-stock',
                roles: [ 'Drive.Sales' ],
                deleted: false,
                created_at: '2020-03-12T17:38:28.055Z',
                updated_at: '2020-03-23T15:33:34.022Z',
                order: 19,
            },
        ],
        children_icons: [ 'home' ],
        children_names: [ 'Comercial' ],
    },
    {
        _id: '5dc990901c669808f31fead4',
        code: 'analytic',
        status: '',
        name: 'Analitica',
        icon: 'equalizer',
        url: 'https://driveweb.axinocp1.central.inditex.grp/analytics/home',
        roles: [ 'Drive.Analytics' ],
        deleted: false,
        created_at: '2019-11-11T16:47:12.929Z',
        updated_at: '2019-11-11T16:47:12.929Z',
        order: 3,
    },
    {
        _id: '5dc013027aa08059f5e800a8',
        code: 'forecast_sales',
        status: '',
        name: 'Predicción',
        icon: 'timeline',
        url: 'https://driveweb.axinocp1.central.inditex.grp/forecast/sales',
        roles: [ 'Drive.Forecast' ],
        deleted: false,
        created_at: '2019-11-04T12:01:06.957Z',
        updated_at: '2019-11-04T12:01:06.957Z',
        order: 4,
        parent: true,
        children: [
            {
                _id: '5dc013027aa08059f5e800a8',
                code: 'forecast_sales',
                status: '',
                name: 'Comercial',
                icon: 'local_offer',
                url: 'https://driveweb.axinocp1.central.inditex.grp/forecast/sales',
                roles: [ 'Drive.Forecast' ],
                deleted: false,
                created_at: '2019-11-04T12:01:06.957Z',
                updated_at: '2019-11-04T12:01:06.957Z',
                order: 4,
            },
            {
                _id: '5dc013247aa0803061e800ac',
                code: 'forecast_hist',
                status: '',
                name: 'Forecast',
                icon: 'timeline',
                url: 'https://driveweb.axinocp1.central.inditex.grp/forecast/hist',
                roles: [ 'Drive.Forecast' ],
                deleted: false,
                created_at: '2019-11-04T12:01:40.184Z',
                updated_at: '2019-11-04T12:01:40.184Z',
                order: 999,
            },
            {
                _id: '5dc013647aa08079b0e800b3',
                code: 'forecast_ware',
                status: '',
                name: 'Forecast',
                icon: 'timeline',
                url: 'https://driveweb.axinocp1.central.inditex.grp/forecast/ware',
                roles: [ 'Drive.Forecast' ],
                deleted: false,
                created_at: '2019-11-04T12:02:44.314Z',
                updated_at: '2019-11-04T12:02:44.314Z',
                order: 999,
            },
        ],
        children_icons: [ 'local_offer' ],
        children_names: [ 'Comercial' ],
    },
    {
        _id: '5dc013367aa08026f9e800ae',
        code: 'budget',
        status: '',
        name: 'Presupuesto',
        icon: 'euro_symbol',
        url: 'https://ecomdriv.axinocp1.central.inditex.grp/budget?brand=1',
        roles: [ 'drive.presupuesto', 'Drive.Sales' ],
        deleted: false,
        created_at: '2019-11-04T12:01:58.297Z',
        updated_at: '2020-04-17T07:59:40.544Z',
        extranet_url: 'https://drive.inditex.com/budget?brand=1',
        order: 5,
    },
    {
        _id: '5dc990851c6698de0b1fead3',
        code: 'warehouses',
        status: '',
        name: 'Almacenes',
        icon: 'apartment',
        url: 'https://ecomdriv.axinocp1.central.inditex.grp/warehouses?brand=1',
        roles: [ 'drive.almacen' ],
        deleted: false,
        created_at: '2019-11-11T16:47:01.710Z',
        updated_at: '2020-04-17T08:08:59.115Z',
        extranet_url: 'https://drive.inditex.com/warehouses?brand=1',
        order: 6,
    },
    {
        _id: '5dc0131c7aa0803307e800ab',
        code: 'returns',
        status: '',
        name: 'Devoluciones',
        icon: 'refresh',
        url: 'https://ecomdriv.axinocp1.central.inditex.grp/devos?brand=1',
        roles: [ 'drive.devos' ],
        deleted: false,
        created_at: '2019-11-04T12:01:32.270Z',
        updated_at: '2020-04-17T08:08:12.663Z',
        extranet_url: 'https://drive.inditex.com/devos?brand=1',
        order: 8,
    },
    {
        _id: '5dc0135b7aa080e7b9e800b2',
        code: 'deliveries',
        status: '',
        name: 'Entregas',
        icon: 'local_shipping',
        url: 'https://ecomdriv.axinocp1.central.inditex.grp/entregas?brand=1',
        roles: [ 'drive.entregas' ],
        deleted: false,
        created_at: '2019-11-04T12:02:35.399Z',
        updated_at: '2020-04-17T08:01:18.442Z',
        extranet_url: 'https://drive.inditex.com/entregas?brand=1',
        order: 9,
    },
    {
        _id: '5dc012f87aa0802487e800a7',
        code: 'logistics',
        status: '',
        name: 'Logística',
        icon: 'emoji_transportation',
        url: 'https://ecomdriv.axinocp1.central.inditex.grp/logistica?brand=1',
        roles: [ 'drive.logistica' ],
        deleted: false,
        created_at: '2019-11-04T12:00:56.944Z',
        updated_at: '2020-04-17T08:04:43.219Z',
        extranet_url: 'https://drive.inditex.com/logistica?brand=1',
        order: 10,
    },
    {
        _id: '5dc013507aa0808f7ce800b1',
        code: 'plato',
        status: '',
        name: 'Plató',
        icon: 'camera',
        url: 'http://axinweb/APPWEB-ZaraDrive/static/plato.html?brand=1',
        roles: [ 'drive.plato' ],
        deleted: false,
        created_at: '2019-11-04T12:02:24.727Z',
        updated_at: '2020-04-17T08:07:29.336Z',
        extranet_url: 'http://axinweb/APPWEB-ZaraDrive/static/plato.html?brand=1',
        order: 11,
    },
    {
        _id: '5dc28c814a48d5369ffc096c',
        code: 'live',
        status: '',
        name: 'Live',
        icon: 'show_chart',
        url: 'https://ecomdriv.axinocp1.central.inditex.grp/live?brand=1',
        roles: [ 'drive.live' ],
        deleted: false,
        created_at: '2019-11-06T09:04:01.451Z',
        updated_at: '2020-04-17T08:02:41.445Z',
        extranet_url: 'https://drive.inditex.com/live?brand=1',
        order: 12,
    },
    {
        _id: '5dc0130a7aa0803054e800a9',
        code: 'live_global',
        status: '',
        name: 'Live global',
        icon: 'public',
        url: 'http://axinweb/APPWEB-ZaraDrive/static/live-global?brand=1',
        roles: [ 'drive.live_global' ],
        deleted: false,
        created_at: '2019-11-04T12:01:14.723Z',
        updated_at: '2019-11-04T12:01:14.723Z',
        order: 13,
    },
    {
        _id: '5dc0132c7aa0806ddbe800ad',
        code: 'overlay',
        status: '',
        name: 'Overlay',
        icon: 'file_copy',
        url: 'https://ecomovev.axinocp1.central.inditex.grp/',
        roles: [ 'drive.overlay' ],
        deleted: false,
        created_at: '2019-11-04T12:01:48.745Z',
        updated_at: '2020-04-17T08:06:26.329Z',
        extranet_url: 'https://overlay.inditex.com/',
        order: 14,
    },
    {
        _id: '5dc013757aa0809196e800b5',
        code: 'admin',
        status: '',
        name: 'Administracion',
        icon: 'settings_applications',
        url: 'https://ecomdriv.axinocp1.central.inditex.grp/admin',
        roles: [ 'drive.admin' ],
        deleted: false,
        created_at: '2019-11-04T12:03:01.313Z',
        updated_at: '2019-11-04T12:03:01.313Z',
        order: 15,
    },
    {
        _id: '5dc02fb77aa080c242e800b7',
        code: 'live_config',
        status: '',
        name: 'Live config',
        icon: 'settings_applications',
        url: 'https://ecomdriv.axinocp1.central.inditex.grp/liveconfig',
        roles: [ 'drive.live_config' ],
        deleted: false,
        created_at: '2019-11-04T14:03:35.567Z',
        updated_at: '2019-11-04T14:03:35.567Z',
        order: 999,
    },
    {
        _id: '6012dbf2ab3316bafc2f7b3e',
        code: 'marketplaces',
        status: 'beta',
        name: 'Marketplaces',
        icon: 'storefront',
        url: 'https://drfrcomr-analytics-za.axinocp1.central.inditex.grp/drfrcomr/marketplaces/home',
        extranet_url: 'https://drive.inditex.com/drfrcomr/marketplaces/home',
        roles: [ 'Drive.Marketplaces' ],
        deleted: false,
        created_at: '2021-01-28T15:44:50.540Z',
        updated_at: '2021-02-10T08:15:06.552Z',
        order: 999,
    },
    {
        _id: '5f744a7bbc03a3c7cb302622',
        code: 'visibility',
        status: 'beta',
        name: 'Visibility',
        icon: 'visibility',
        url: 'https://drfrcomr-analytics-za.axinocp1.central.inditex.grp/drfrcomr/visibility/home',
        extranet_url: 'https://drive.inditex.com/drfrcomr/visibility/home',
        roles: [ 'Drive.WebVisibility' ],
        deleted: false,
        created_at: '2020-09-30T09:06:03.350Z',
        updated_at: '2020-10-01T12:31:48.755Z',
        order: 999,
    },
];
