/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Brands, ComplexSelectorOptions, FilterOptionHeader, FiltersConfig, Row, Screen, SelectedFilter, SelectorOption, Tab, TabStyle, TimelineEvent, UIInterface, UserData } from "glyph-core";
import { ExpandRowEvent } from "./components/list/list.model";
export namespace Components {
    interface GlyphAppMenu {
        /**
          * List of apps
         */
        "apps": Screen[];
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback": () => void;
    }
    interface GlyphAvatar {
        /**
          * User avatar image
         */
        "image": UserData['image'];
        /**
          * User name, used as image fallback
         */
        "name": UserData['name'];
    }
    interface GlyphButton {
        /**
          * Material icons id
         */
        "icon": string;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": UIInterface;
        /**
          * Button text
         */
        "text": string;
    }
    interface GlyphChipsbar {
        /**
          * Filters configuration object
         */
        "filtersConfig": FiltersConfig;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type [ 'MODERN', 'CLASSIC' ]
         */
        "interface": UIInterface;
    }
    interface GlyphFilter {
        /**
          * Filter description
         */
        "description": string;
        /**
          * Multiselect flag. True if filter allows multiselect toggler
         */
        "haveMultiSelect": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface": UIInterface;
        /**
          * This flag is true if multiselect is active
         */
        "multiSelect": boolean;
        /**
          * Filter options
         */
        "options": FilterOptionHeader[];
        /**
          * Filter plural
         */
        "plural": string;
        /**
          * Search placeholder
         */
        "searchPlaceholder": string;
        /**
          * Filter selected
         */
        "selected": SelectedFilter[];
    }
    interface GlyphFilterOptions {
        /**
          * Close callback
         */
        "closeEvent": () => void;
        /**
          * Filter description
         */
        "description": string;
        /**
          * Multiselect flag. True if filter allows multiselect toggler
         */
        "haveMultiSelect": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface": UIInterface;
        /**
          * This flag is true if multiselect is active
         */
        "multiSelect": boolean;
        /**
          * Multiselect toggler callback
         */
        "multiSelectEvent": () => void;
        /**
          * Option click event
         */
        "optionClickEvent": (option: FilterOptionHeader) => void;
        /**
          * Filter options
         */
        "options": FilterOptionHeader[];
        /**
          * Search placeholder
         */
        "searchPlaceholder": string;
    }
    interface GlyphHeader {
        /**
          * Application brand
         */
        "activeBrand": Brands;
        /**
          * Apps data
         */
        "appData": Screen[];
        /**
          * Application subtitle
         */
        "appSubtitle": string;
        /**
          * Application title
         */
        "appTitle": string;
        /**
          * User avatar flag
         */
        "avatar": boolean;
        /**
          * Brand selector flag
         */
        "brand": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": UIInterface;
        /**
          * View menu flag
         */
        "menu": boolean;
        /**
          * Notification flag
         */
        "notifications": boolean;
        /**
          * Search flag
         */
        "search": boolean;
        /**
          * Share menu flag
         */
        "share": boolean;
        /**
          * Timeline flag
         */
        "timeline": boolean;
        /**
          * User data
         */
        "userData": UserData;
    }
    interface GlyphList {
        /**
          * Component data. Fields preffixed with `_` will not render
         */
        "data": Row[];
        /**
          * Show decimals flag
         */
        "decimals": boolean;
        /**
          * Default sorting field, it could be a private or public field
         */
        "defaultSortField": string;
        /**
          * Enable download xlsx file
         */
        "enableDownload": boolean;
        /**
          * Expandable flag
         */
        "expandable": boolean;
        /**
          * Rows that has no data on these fields will not render
         */
        "filterFields": string[];
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Rows limit. If not set will take `16` as default value or `10` in small screens
         */
        "limit": number;
        /**
          * Loading state. If true will render skeleton loader
         */
        "loading": boolean;
        /**
          * Force component update if flag is true
         */
        "update": boolean;
    }
    interface GlyphListRow {
        /**
          * expand row callback
         */
        "expandHandle": (row: Row) => () => any;
        /**
          * expandable flag
         */
        "expandable": boolean;
        /**
          * Render fields
         */
        "fields": string[];
        /**
          * i18n object with translations
         */
        "i18n": any;
        /**
          * total flag
         */
        "isTotal": boolean;
        /**
          * row data
         */
        "row": Row;
    }
    interface GlyphNoData {
        /**
          * Bottom text. only applies if render mode is advanced
         */
        "bottomText": string;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Render mode [ 'simple' | 'complex' ]
         */
        "mode": string;
        /**
          * Top text only applies if render mode is advanced
         */
        "text": string;
    }
    interface GlyphSelector {
        /**
          * Complex selector options
         */
        "complexOptions": ComplexSelectorOptions;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": UIInterface;
        /**
          * Selector label
         */
        "label": string;
        /**
          * Multiselect flag
         */
        "multiSelect": boolean;
        /**
          * Selector options
         */
        "options": SelectorOption[];
    }
    interface GlyphShareMenu {
        /**
          * Application subtitle
         */
        "appSubtitle": string;
        /**
          * Application title
         */
        "appTitle": string;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": UIInterface;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback": () => void;
    }
    interface GlyphSkLoader {
        /**
          * Height of loader line
         */
        "height": number;
        /**
          * Number of loader lines that will be rendered
         */
        "repetitions": number;
    }
    interface GlyphTabs {
        /**
          * Tab rendering style big | small
         */
        "tabStyle": TabStyle;
        /**
          * Component tabs
         */
        "tabs": Tab[];
    }
    interface GlyphTimeline {
        /**
          * Timeline events
         */
        "events": TimelineEvent[];
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": UIInterface;
    }
    interface GlyphTitle {
        /**
          * title text
         */
        "titleText": string;
    }
    interface GlyphToaster {
        /**
          * Id of event that trigger toaster show
         */
        "eventId": string;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Time to live for shown toaster
         */
        "ttl": number;
    }
    interface GlyphToggler {
        /**
          * Toggler state
         */
        "active": boolean;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": UIInterface;
    }
    interface GlyphUserMenu {
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * User name
         */
        "name": string;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback": () => void;
    }
}
declare global {
    interface HTMLGlyphAppMenuElement extends Components.GlyphAppMenu, HTMLStencilElement {
    }
    var HTMLGlyphAppMenuElement: {
        prototype: HTMLGlyphAppMenuElement;
        new (): HTMLGlyphAppMenuElement;
    };
    interface HTMLGlyphAvatarElement extends Components.GlyphAvatar, HTMLStencilElement {
    }
    var HTMLGlyphAvatarElement: {
        prototype: HTMLGlyphAvatarElement;
        new (): HTMLGlyphAvatarElement;
    };
    interface HTMLGlyphButtonElement extends Components.GlyphButton, HTMLStencilElement {
    }
    var HTMLGlyphButtonElement: {
        prototype: HTMLGlyphButtonElement;
        new (): HTMLGlyphButtonElement;
    };
    interface HTMLGlyphChipsbarElement extends Components.GlyphChipsbar, HTMLStencilElement {
    }
    var HTMLGlyphChipsbarElement: {
        prototype: HTMLGlyphChipsbarElement;
        new (): HTMLGlyphChipsbarElement;
    };
    interface HTMLGlyphFilterElement extends Components.GlyphFilter, HTMLStencilElement {
    }
    var HTMLGlyphFilterElement: {
        prototype: HTMLGlyphFilterElement;
        new (): HTMLGlyphFilterElement;
    };
    interface HTMLGlyphFilterOptionsElement extends Components.GlyphFilterOptions, HTMLStencilElement {
    }
    var HTMLGlyphFilterOptionsElement: {
        prototype: HTMLGlyphFilterOptionsElement;
        new (): HTMLGlyphFilterOptionsElement;
    };
    interface HTMLGlyphHeaderElement extends Components.GlyphHeader, HTMLStencilElement {
    }
    var HTMLGlyphHeaderElement: {
        prototype: HTMLGlyphHeaderElement;
        new (): HTMLGlyphHeaderElement;
    };
    interface HTMLGlyphListElement extends Components.GlyphList, HTMLStencilElement {
    }
    var HTMLGlyphListElement: {
        prototype: HTMLGlyphListElement;
        new (): HTMLGlyphListElement;
    };
    interface HTMLGlyphListRowElement extends Components.GlyphListRow, HTMLStencilElement {
    }
    var HTMLGlyphListRowElement: {
        prototype: HTMLGlyphListRowElement;
        new (): HTMLGlyphListRowElement;
    };
    interface HTMLGlyphNoDataElement extends Components.GlyphNoData, HTMLStencilElement {
    }
    var HTMLGlyphNoDataElement: {
        prototype: HTMLGlyphNoDataElement;
        new (): HTMLGlyphNoDataElement;
    };
    interface HTMLGlyphSelectorElement extends Components.GlyphSelector, HTMLStencilElement {
    }
    var HTMLGlyphSelectorElement: {
        prototype: HTMLGlyphSelectorElement;
        new (): HTMLGlyphSelectorElement;
    };
    interface HTMLGlyphShareMenuElement extends Components.GlyphShareMenu, HTMLStencilElement {
    }
    var HTMLGlyphShareMenuElement: {
        prototype: HTMLGlyphShareMenuElement;
        new (): HTMLGlyphShareMenuElement;
    };
    interface HTMLGlyphSkLoaderElement extends Components.GlyphSkLoader, HTMLStencilElement {
    }
    var HTMLGlyphSkLoaderElement: {
        prototype: HTMLGlyphSkLoaderElement;
        new (): HTMLGlyphSkLoaderElement;
    };
    interface HTMLGlyphTabsElement extends Components.GlyphTabs, HTMLStencilElement {
    }
    var HTMLGlyphTabsElement: {
        prototype: HTMLGlyphTabsElement;
        new (): HTMLGlyphTabsElement;
    };
    interface HTMLGlyphTimelineElement extends Components.GlyphTimeline, HTMLStencilElement {
    }
    var HTMLGlyphTimelineElement: {
        prototype: HTMLGlyphTimelineElement;
        new (): HTMLGlyphTimelineElement;
    };
    interface HTMLGlyphTitleElement extends Components.GlyphTitle, HTMLStencilElement {
    }
    var HTMLGlyphTitleElement: {
        prototype: HTMLGlyphTitleElement;
        new (): HTMLGlyphTitleElement;
    };
    interface HTMLGlyphToasterElement extends Components.GlyphToaster, HTMLStencilElement {
    }
    var HTMLGlyphToasterElement: {
        prototype: HTMLGlyphToasterElement;
        new (): HTMLGlyphToasterElement;
    };
    interface HTMLGlyphTogglerElement extends Components.GlyphToggler, HTMLStencilElement {
    }
    var HTMLGlyphTogglerElement: {
        prototype: HTMLGlyphTogglerElement;
        new (): HTMLGlyphTogglerElement;
    };
    interface HTMLGlyphUserMenuElement extends Components.GlyphUserMenu, HTMLStencilElement {
    }
    var HTMLGlyphUserMenuElement: {
        prototype: HTMLGlyphUserMenuElement;
        new (): HTMLGlyphUserMenuElement;
    };
    interface HTMLElementTagNameMap {
        "glyph-app-menu": HTMLGlyphAppMenuElement;
        "glyph-avatar": HTMLGlyphAvatarElement;
        "glyph-button": HTMLGlyphButtonElement;
        "glyph-chipsbar": HTMLGlyphChipsbarElement;
        "glyph-filter": HTMLGlyphFilterElement;
        "glyph-filter-options": HTMLGlyphFilterOptionsElement;
        "glyph-header": HTMLGlyphHeaderElement;
        "glyph-list": HTMLGlyphListElement;
        "glyph-list-row": HTMLGlyphListRowElement;
        "glyph-no-data": HTMLGlyphNoDataElement;
        "glyph-selector": HTMLGlyphSelectorElement;
        "glyph-share-menu": HTMLGlyphShareMenuElement;
        "glyph-sk-loader": HTMLGlyphSkLoaderElement;
        "glyph-tabs": HTMLGlyphTabsElement;
        "glyph-timeline": HTMLGlyphTimelineElement;
        "glyph-title": HTMLGlyphTitleElement;
        "glyph-toaster": HTMLGlyphToasterElement;
        "glyph-toggler": HTMLGlyphTogglerElement;
        "glyph-user-menu": HTMLGlyphUserMenuElement;
    }
}
declare namespace LocalJSX {
    interface GlyphAppMenu {
        /**
          * List of apps
         */
        "apps"?: Screen[];
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback"?: () => void;
    }
    interface GlyphAvatar {
        /**
          * User avatar image
         */
        "image"?: UserData['image'];
        /**
          * User name, used as image fallback
         */
        "name"?: UserData['name'];
    }
    interface GlyphButton {
        /**
          * Material icons id
         */
        "icon"?: string;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: UIInterface;
        /**
          * Button text
         */
        "text"?: string;
    }
    interface GlyphChipsbar {
        /**
          * Filters configuration object
         */
        "filtersConfig"?: FiltersConfig;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type [ 'MODERN', 'CLASSIC' ]
         */
        "interface"?: UIInterface;
        /**
          * Clear all filters event
         */
        "onClearAll"?: (event: CustomEvent<any>) => void;
        /**
          * Filter clear event
         */
        "onFilterClear"?: (event: CustomEvent<any>) => void;
        /**
          * Filter multiselect event
         */
        "onFilterMultiSelect"?: (event: CustomEvent<any>) => void;
        /**
          * Filter select event
         */
        "onFilterSelect"?: (event: CustomEvent<any>) => void;
    }
    interface GlyphFilter {
        /**
          * Filter description
         */
        "description"?: string;
        /**
          * Multiselect flag. True if filter allows multiselect toggler
         */
        "haveMultiSelect"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface"?: UIInterface;
        /**
          * This flag is true if multiselect is active
         */
        "multiSelect"?: boolean;
        /**
          * Clear selected filters callback
         */
        "onClearEvent"?: (event: CustomEvent<any>) => void;
        /**
          * Multiselect toggler callback
         */
        "onMultiSelectEvent"?: (event: CustomEvent<any>) => void;
        /**
          * Option click event
         */
        "onOptionClickEvent"?: (event: CustomEvent<any>) => void;
        /**
          * Filter options
         */
        "options"?: FilterOptionHeader[];
        /**
          * Filter plural
         */
        "plural"?: string;
        /**
          * Search placeholder
         */
        "searchPlaceholder"?: string;
        /**
          * Filter selected
         */
        "selected"?: SelectedFilter[];
    }
    interface GlyphFilterOptions {
        /**
          * Close callback
         */
        "closeEvent"?: () => void;
        /**
          * Filter description
         */
        "description"?: string;
        /**
          * Multiselect flag. True if filter allows multiselect toggler
         */
        "haveMultiSelect"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface"?: UIInterface;
        /**
          * This flag is true if multiselect is active
         */
        "multiSelect"?: boolean;
        /**
          * Multiselect toggler callback
         */
        "multiSelectEvent"?: () => void;
        /**
          * Option click event
         */
        "optionClickEvent"?: (option: FilterOptionHeader) => void;
        /**
          * Filter options
         */
        "options"?: FilterOptionHeader[];
        /**
          * Search placeholder
         */
        "searchPlaceholder"?: string;
    }
    interface GlyphHeader {
        /**
          * Application brand
         */
        "activeBrand"?: Brands;
        /**
          * Apps data
         */
        "appData"?: Screen[];
        /**
          * Application subtitle
         */
        "appSubtitle"?: string;
        /**
          * Application title
         */
        "appTitle"?: string;
        /**
          * User avatar flag
         */
        "avatar"?: boolean;
        /**
          * Brand selector flag
         */
        "brand"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: UIInterface;
        /**
          * View menu flag
         */
        "menu"?: boolean;
        /**
          * Notification flag
         */
        "notifications"?: boolean;
        /**
          * Search flag
         */
        "search"?: boolean;
        /**
          * Share menu flag
         */
        "share"?: boolean;
        /**
          * Timeline flag
         */
        "timeline"?: boolean;
        /**
          * User data
         */
        "userData"?: UserData;
    }
    interface GlyphList {
        /**
          * Component data. Fields preffixed with `_` will not render
         */
        "data"?: Row[];
        /**
          * Show decimals flag
         */
        "decimals"?: boolean;
        /**
          * Default sorting field, it could be a private or public field
         */
        "defaultSortField"?: string;
        /**
          * Enable download xlsx file
         */
        "enableDownload"?: boolean;
        /**
          * Expandable flag
         */
        "expandable"?: boolean;
        /**
          * Rows that has no data on these fields will not render
         */
        "filterFields"?: string[];
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Rows limit. If not set will take `16` as default value or `10` in small screens
         */
        "limit"?: number;
        /**
          * Loading state. If true will render skeleton loader
         */
        "loading"?: boolean;
        /**
          * Expand row event
         */
        "onExpandRow"?: (event: CustomEvent<ExpandRowEvent>) => void;
        /**
          * Force component update if flag is true
         */
        "update"?: boolean;
    }
    interface GlyphListRow {
        /**
          * expand row callback
         */
        "expandHandle"?: (row: Row) => () => any;
        /**
          * expandable flag
         */
        "expandable"?: boolean;
        /**
          * Render fields
         */
        "fields"?: string[];
        /**
          * i18n object with translations
         */
        "i18n"?: any;
        /**
          * total flag
         */
        "isTotal"?: boolean;
        /**
          * row data
         */
        "row"?: Row;
    }
    interface GlyphNoData {
        /**
          * Bottom text. only applies if render mode is advanced
         */
        "bottomText"?: string;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Render mode [ 'simple' | 'complex' ]
         */
        "mode"?: string;
        /**
          * Top text only applies if render mode is advanced
         */
        "text"?: string;
    }
    interface GlyphSelector {
        /**
          * Complex selector options
         */
        "complexOptions"?: ComplexSelectorOptions;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: UIInterface;
        /**
          * Selector label
         */
        "label"?: string;
        /**
          * Multiselect flag
         */
        "multiSelect"?: boolean;
        /**
          * on change callback
         */
        "onOptionSelect"?: (event: CustomEvent<SelectorOption>) => void;
        /**
          * Selector options
         */
        "options"?: SelectorOption[];
    }
    interface GlyphShareMenu {
        /**
          * Application subtitle
         */
        "appSubtitle"?: string;
        /**
          * Application title
         */
        "appTitle"?: string;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: UIInterface;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback"?: () => void;
    }
    interface GlyphSkLoader {
        /**
          * Height of loader line
         */
        "height"?: number;
        /**
          * Number of loader lines that will be rendered
         */
        "repetitions"?: number;
    }
    interface GlyphTabs {
        /**
          * Tab selection event
         */
        "onTabSelect"?: (event: CustomEvent<Tab>) => void;
        /**
          * Tab rendering style big | small
         */
        "tabStyle"?: TabStyle;
        /**
          * Component tabs
         */
        "tabs"?: Tab[];
    }
    interface GlyphTimeline {
        /**
          * Timeline events
         */
        "events"?: TimelineEvent[];
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: UIInterface;
    }
    interface GlyphTitle {
        /**
          * title text
         */
        "titleText"?: string;
    }
    interface GlyphToaster {
        /**
          * Id of event that trigger toaster show
         */
        "eventId"?: string;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Time to live for shown toaster
         */
        "ttl"?: number;
    }
    interface GlyphToggler {
        /**
          * Toggler state
         */
        "active"?: boolean;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: UIInterface;
    }
    interface GlyphUserMenu {
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * User name
         */
        "name"?: string;
        /**
          * Logout event, trigger an event identified with **logout** key
         */
        "onLogout"?: (event: CustomEvent<any>) => void;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback"?: () => void;
    }
    interface IntrinsicElements {
        "glyph-app-menu": GlyphAppMenu;
        "glyph-avatar": GlyphAvatar;
        "glyph-button": GlyphButton;
        "glyph-chipsbar": GlyphChipsbar;
        "glyph-filter": GlyphFilter;
        "glyph-filter-options": GlyphFilterOptions;
        "glyph-header": GlyphHeader;
        "glyph-list": GlyphList;
        "glyph-list-row": GlyphListRow;
        "glyph-no-data": GlyphNoData;
        "glyph-selector": GlyphSelector;
        "glyph-share-menu": GlyphShareMenu;
        "glyph-sk-loader": GlyphSkLoader;
        "glyph-tabs": GlyphTabs;
        "glyph-timeline": GlyphTimeline;
        "glyph-title": GlyphTitle;
        "glyph-toaster": GlyphToaster;
        "glyph-toggler": GlyphToggler;
        "glyph-user-menu": GlyphUserMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "glyph-app-menu": LocalJSX.GlyphAppMenu & JSXBase.HTMLAttributes<HTMLGlyphAppMenuElement>;
            "glyph-avatar": LocalJSX.GlyphAvatar & JSXBase.HTMLAttributes<HTMLGlyphAvatarElement>;
            "glyph-button": LocalJSX.GlyphButton & JSXBase.HTMLAttributes<HTMLGlyphButtonElement>;
            "glyph-chipsbar": LocalJSX.GlyphChipsbar & JSXBase.HTMLAttributes<HTMLGlyphChipsbarElement>;
            "glyph-filter": LocalJSX.GlyphFilter & JSXBase.HTMLAttributes<HTMLGlyphFilterElement>;
            "glyph-filter-options": LocalJSX.GlyphFilterOptions & JSXBase.HTMLAttributes<HTMLGlyphFilterOptionsElement>;
            "glyph-header": LocalJSX.GlyphHeader & JSXBase.HTMLAttributes<HTMLGlyphHeaderElement>;
            "glyph-list": LocalJSX.GlyphList & JSXBase.HTMLAttributes<HTMLGlyphListElement>;
            "glyph-list-row": LocalJSX.GlyphListRow & JSXBase.HTMLAttributes<HTMLGlyphListRowElement>;
            "glyph-no-data": LocalJSX.GlyphNoData & JSXBase.HTMLAttributes<HTMLGlyphNoDataElement>;
            "glyph-selector": LocalJSX.GlyphSelector & JSXBase.HTMLAttributes<HTMLGlyphSelectorElement>;
            "glyph-share-menu": LocalJSX.GlyphShareMenu & JSXBase.HTMLAttributes<HTMLGlyphShareMenuElement>;
            "glyph-sk-loader": LocalJSX.GlyphSkLoader & JSXBase.HTMLAttributes<HTMLGlyphSkLoaderElement>;
            "glyph-tabs": LocalJSX.GlyphTabs & JSXBase.HTMLAttributes<HTMLGlyphTabsElement>;
            "glyph-timeline": LocalJSX.GlyphTimeline & JSXBase.HTMLAttributes<HTMLGlyphTimelineElement>;
            "glyph-title": LocalJSX.GlyphTitle & JSXBase.HTMLAttributes<HTMLGlyphTitleElement>;
            "glyph-toaster": LocalJSX.GlyphToaster & JSXBase.HTMLAttributes<HTMLGlyphToasterElement>;
            "glyph-toggler": LocalJSX.GlyphToggler & JSXBase.HTMLAttributes<HTMLGlyphTogglerElement>;
            "glyph-user-menu": LocalJSX.GlyphUserMenu & JSXBase.HTMLAttributes<HTMLGlyphUserMenuElement>;
        }
    }
}
