/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Alignment, Article, Brand, Brands, Button, ButtonGroupStyle, ComparableType, ComplexSelectorOptions, Crumb, FilterOptionHeader, FiltersConfig, FilterSelectEvent, FilterUpdateEvent, RankingData, RankingViewOptions, Row, Screen, SelectorOption, SortableChildrenEvent, SortableOption, Tab, TabStyle, TimelineEvent, UITheme, UserData, UserMenuConfiguration } from "glyph-core-poc";
import { SortableOptions } from "sortablejs";
export namespace Components {
    interface GlyphAppMenu {
        /**
          * List of apps
         */
        "apps": Screen[];
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Flag to activate search input
         */
        "hasSearch": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback": () => void;
    }
    interface GlyphArticle {
        /**
          * Article data
         */
        "article": Article;
        /**
          * Aspect ratio used to calculate loader height
         */
        "aspectRatio": number;
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * This method will return image height
         */
        "getImageSize": () => Promise<DOMRect>;
        /**
          * This method will hide tooltip
         */
        "hideTooltip": () => Promise<void>;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Image type to render image | plain_image
         */
        "imageType": string;
        /**
          * Flag to activate click callback
         */
        "isClickable": boolean;
        /**
          * Force visibility flag
         */
        "isVisible": Boolean;
        /**
          * Loading flag
         */
        "loading": boolean;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * **optional** Compose image url callback
         */
        "parseImageUrl": (image: string) => string;
        /**
          * Field to render quantity tag
         */
        "quantityField": string;
        /**
          * This method will hide tooltip
         */
        "setArticleSize": () => Promise<void>;
        /**
          * Decorate with backdrop filter, solves some performance issues (in storybook)
         */
        "useBackdropDecoration": boolean;
    }
    interface GlyphAvatar {
        /**
          * User avatar image
         */
        "image": UserData['image'];
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * User name, used as image fallback
         */
        "name": UserData['name'];
    }
    interface GlyphBrandList {
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Brand list
         */
        "brandList": Brand[];
        /**
          * Event triggered when user clicks outside
         */
        "outsideCallback": () => void;
    }
    interface GlyphBreadcrumbs {
        /**
          * Crumb property. Last one is displayed as active. Each crumb triggers a callback on click
         */
        "crumbs": Crumb[];
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
    }
    interface GlyphButton {
        /**
          * Action button. Displayed with text only
         */
        "action": boolean;
        /**
          * Cancel type button. Renders in red
         */
        "cancel": boolean;
        /**
          * Custom classNames to apply
         */
        "class": string;
        /**
          * Material icons id
         */
        "icon": string;
        /**
          * Renders icon first
         */
        "iconFirst": boolean;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Button text
         */
        "text": string;
        /**
          * Tiny action button displays a smaller and thinier text
         */
        "tiny": boolean;
    }
    interface GlyphButtonGroup {
        /**
          * Button alignment ['left', 'center', 'right']
         */
        "alignment": Alignment;
        /**
          * Buttons configuration
         */
        "buttons": Button[];
        /**
          * Application interface
         */
        "interface": string;
        /**
          * Button group size ['big', 'small']
         */
        "size": ButtonGroupStyle;
    }
    interface GlyphCalendar {
        /**
          * Activate seconday selection display
         */
        "auxActive": boolean;
        /**
          * Selected end date
         */
        "endDate": Date;
        /**
          * Secondary selected end date
         */
        "endDateAux": Date;
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Maximum allowed date
         */
        "maxDate": Date;
        /**
          * Maximum allowed date
         */
        "maxDateAux": Date;
        /**
          * Minimum allowed date
         */
        "minDate": Date;
        /**
          * Minimum allowed date
         */
        "minDateAux": Date;
        /**
          * Number of months to be shown. 2 by default
         */
        "months": number;
        /**
          * Secondary selection. Shows selection in orange. **requires auxActive**
         */
        "secondary": boolean;
        /**
          * Allow single day selection
         */
        "singleSelect": boolean;
        /**
          * Selected start date
         */
        "startDate": Date;
        /**
          * Secondary selected start date
         */
        "startDateAux": Date;
    }
    interface GlyphChipsbar {
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Filters configuration object
         */
        "filtersConfig": FiltersConfig;
        /**
          * Hide zara south filters active
         */
        "hideZaraSouth": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type
         */
        "interface": string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
    }
    interface GlyphConfigModal {
        /**
          * Filters configuration
         */
        "filtersConfig": FiltersConfig;
        /**
          * Hide zara south filters active
         */
        "hideZaraSouth": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type [ 'MODERN', 'CLASSIC' ]
         */
        "interface": string;
    }
    interface GlyphDateFilter {
        /**
          * Active flag
         */
        "active": boolean;
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * This method will return image height
         */
        "clearFilter": () => Promise<void>;
        /**
          * Comparable options
         */
        "comparableOptions": SelectorOption[];
        /**
          * Comparabel type
         */
        "comparableType": ComparableType;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * Maximum available comp date
         */
        "maxComparableDate": Date;
        /**
          * Maximum available date
         */
        "maxDate": Date;
        /**
          * Minimum available comp date
         */
        "minComparableDate": Date;
        /**
          * Minimum available date
         */
        "minDate": Date;
        /**
          * Number of months to be shown. 2 by default
         */
        "months": number;
        /**
          * Filter options
         */
        "options": FilterOptionHeader[];
        /**
          * Allow single day selection
         */
        "singleSelect": boolean;
    }
    interface GlyphFilter {
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * This method will return image height
         */
        "clearFilter": () => Promise<void>;
        /**
          * Filter description
         */
        "description": string;
        /**
          * Multiselect flag. True if filter allows multiselect toggler
         */
        "haveMultiSelect": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * This flag is true if multiselect is active
         */
        "multiSelect": boolean;
        /**
          * Filter options
         */
        "options": FilterOptionHeader[];
        /**
          * Filter plural
         */
        "plural": string;
        /**
          * Search placeholder
         */
        "searchPlaceholder": string;
    }
    interface GlyphFilterDrilldownOptions {
        /**
          * Expanded flag
         */
        "expanded": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Filter options
         */
        "option": FilterOptionHeader;
        /**
          * Option click event
         */
        "optionClick": (option: FilterOptionHeader) => (event: any) => void;
        /**
          * Search value
         */
        "searchValue": string;
    }
    interface GlyphFilterOptions {
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Close callback
         */
        "closeEvent": () => void;
        /**
          * Filter description
         */
        "description": string;
        /**
          * Multiselect flag. True if filter allows multiselect toggler
         */
        "haveMultiSelect": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * This flag is true if multiselect is active
         */
        "multiSelect": boolean;
        /**
          * Multiselect toggler callback
         */
        "multiSelectEvent": () => void;
        /**
          * Option click event
         */
        "optionClickEvent": (option: FilterOptionHeader) => void;
        /**
          * Filter options
         */
        "options": FilterOptionHeader[];
        /**
          * Search placeholder
         */
        "searchPlaceholder": string;
    }
    interface GlyphFilterOptionsList {
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Style applied in list
         */
        "listStyle": { [key: string]: string };
        /**
          * Option click event
         */
        "optionClick": (option: FilterOptionHeader) => (event: any) => void;
        /**
          * Filter options
         */
        "options": FilterOptionHeader[];
        /**
          * Search value
         */
        "searchValue": string;
    }
    interface GlyphFlex {
        /**
          * Apply spaced around distribution
         */
        "around": boolean;
        /**
          * Verical align = bottom
         */
        "bottom": boolean;
        /**
          * Horizontal align = center
         */
        "center": boolean;
        /**
          * Flex-direction = vertical
         */
        "column": boolean;
        /**
          * Class attribute to apply in flex div
         */
        "flexClass": string;
        /**
          * Id attribute to apply in flex div
         */
        "flexId": string;
        /**
          * Style atttribute to apply in flex div
         */
        "flexStyle": any;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Horizonal align = left
         */
        "left": boolean;
        /**
          * Vertical align = middle
         */
        "middle": boolean;
        /**
          * Horizontal align = right
         */
        "right": boolean;
        /**
          * Flex-direction = horizontal
         */
        "row": boolean;
        /**
          * Apply spaced distribution
         */
        "spaced": boolean;
        /**
          * Set an id to attribute data-testid
         */
        "testId": string;
        /**
          * Theme type
         */
        "theme": UITheme;
        /**
          * Vertical align = top
         */
        "top": boolean;
    }
    interface GlyphHeader {
        /**
          * Application brand
         */
        "activeBrand": Brands;
        /**
          * Apps data
         */
        "appData": Screen[];
        /**
          * Application subtitle
         */
        "appSubtitle": string;
        /**
          * Application title
         */
        "appTitle": string;
        /**
          * User avatar flag
         */
        "avatar": boolean;
        /**
          * Brand selector flag
         */
        "brand": boolean;
        /**
          * Available brands list
         */
        "brandList": Brand[];
        /**
          * Calendar events
         */
        "calendarEvents": TimelineEvent[];
        /**
          * Events
         */
        "events": TimelineEvent[];
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * View menu flag
         */
        "menu": boolean;
        /**
          * Notification flag
         */
        "notifications": boolean;
        /**
          * Search flag
         */
        "search": boolean;
        /**
          * Share menu flag
         */
        "share": boolean;
        /**
          * Timeline flag
         */
        "timeline": boolean;
        /**
          * User data
         */
        "userData": UserData;
        /**
          * User menu config
         */
        "userMenuConfig": UserMenuConfiguration;
    }
    interface GlyphIcon {
        /**
          * render icon with button role
         */
        "button": boolean;
        /**
          * class to use in icon
         */
        "class": string;
        /**
          * click callback
         */
        "clickCbk": (event: MouseEvent) => any;
        /**
          * icon name
         */
        "icon": string;
        /**
          * render material icon
         */
        "material": boolean;
        /**
          * render outlined icon (for material icons)
         */
        "outlined": boolean;
    }
    interface GlyphInput {
        /**
          * Input should auto focus
         */
        "autoFocus": boolean;
        /**
          * Renders input in a box
         */
        "box": boolean;
        /**
          * Flag to disable input
         */
        "disabled": boolean;
        /**
          * Style input as an error
         */
        "error": boolean;
        /**
          * Input type
         */
        "inputType": string;
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Maximum availabla for inputs (dates or ranges)
         */
        "max": any;
        /**
          * Minimum available for inputs (dates or ranges)
         */
        "min": any;
        /**
          * Placeholder
         */
        "placeholder": string;
        /**
          * Search flag, renders a search icon if `box` is false
         */
        "search": boolean;
        /**
          * Input value
         */
        "value": any;
    }
    interface GlyphList {
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Component data. Fields preffixed with `_` will not render
         */
        "data": Row[];
        /**
          * Show decimals flag
         */
        "decimals": boolean;
        /**
          * Default sorting field, it could be a private or public field
         */
        "defaultSortField": string;
        /**
          * Enable download xlsx file
         */
        "enableDownload": boolean;
        /**
          * Expandable flag
         */
        "expandable": boolean;
        /**
          * Rows that has no data on these fields will not render
         */
        "filterFields": string[];
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Rows limit. If not set will take `16` as default value or `10` in small screens
         */
        "limit": number;
        /**
          * Loading state. If true will render skeleton loader
         */
        "loading": boolean;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * Number of pages to be grouped if list is larger than limit
         */
        "pageGroups": number;
        /**
          * Pagination limit
         */
        "paginationLimit": number;
        /**
          * Force component update if flag is true
         */
        "update": boolean;
    }
    interface GlyphListRow {
        /**
          * expand row callback
         */
        "expandHandle": (row: Row) => () => any;
        /**
          * expandable flag
         */
        "expandable": boolean;
        /**
          * Render fields
         */
        "fields": string[];
        /**
          * i18n object with translations
         */
        "i18n": any;
        /**
          * total flag
         */
        "isTotal": boolean;
        /**
          * row data
         */
        "row": Row;
    }
    interface GlyphLogin {
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Extra i18n translates
         */
        "i18n": { [key: string]: string };
        /**
          * Component interface *modern* | *classic*
         */
        "interface": string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * Login callback
         */
        "login": (userData: { user: string; password: string }) => void;
        /**
          * On login success
         */
        "loginSuccess": (result: any) => void;
        /**
          * Application version
         */
        "version": string;
    }
    interface GlyphModal {
        /**
          * Apply button text. Renders button if set
         */
        "applyButton": string;
        /**
          * Cancel button text. Renders button if set
         */
        "cancelButton": string;
        /**
          * Close button flag
         */
        "closeButton": boolean;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Modal min height
         */
        "maxHeight": string;
        /**
          * Modal min with
         */
        "maxWidth": string;
        /**
          * Modal title
         */
        "modalTitle": string;
        /**
          * Modal padded flag
         */
        "padded": boolean;
        /**
          * Modal visibility flag
         */
        "visible": boolean;
    }
    interface GlyphNoData {
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Bottom text. only applies if render mode is advanced
         */
        "bottomText": string;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * Render mode [ 'simple' | 'complex' ]
         */
        "mode": string;
        /**
          * Top text only applies if render mode is advanced
         */
        "text": string;
    }
    interface GlyphNotifications {
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback": () => void;
    }
    interface GlyphPagination {
        /**
          * Active page
         */
        "activePage": number;
        /**
          * Pagination limit in first group
         */
        "limit": number;
        /**
          * Number of pages to be grouped if list is larger than limit
         */
        "pageGroups": number;
        /**
          * Number of pages to be rendered
         */
        "pages": number;
    }
    interface GlyphRanking {
        /**
          * Aspect ratio used to calculate loader height
         */
        "aspectRatio": number;
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * This method will change ranking container scroll
         */
        "changeScroll": (scroll?: number, listeneable?: boolean) => Promise<void>;
        /**
          * Distance between columns
         */
        "columnGap": string;
        /**
          * Columns to render if ranking have more than 1 section, number of columns will apply per section
         */
        "columns": number;
        /**
          * Distance applied to both axes
         */
        "gap": string;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Image type to render image | plain_image
         */
        "imageType": string;
        /**
          * Inner columns, sets how many columns should be rendered per column
         */
        "innerColumns": number;
        /**
          * Distance between elements inside a column
         */
        "innerGap": string;
        /**
          * Loading flag
         */
        "loading": boolean;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * **optional** Compose image url callback
         */
        "parseImageUrl": (image: string) => string;
        /**
          * Ranking data
         */
        "rankingData": RankingData[];
        /**
          * (optional) ranking header. Applicable on single section ranking
         */
        "rankingHeader": string;
        /**
          * Distance between rows
         */
        "rowGap": string;
        /**
          * Row to render
         */
        "rows": number;
        /**
          * Decorate with backdrop filter, solves some performance issues (in storybook)
         */
        "useBackdropDecoration": boolean;
    }
    interface GlyphRankingLayout {
        /**
          * Active view layout
         */
        "activeView": RankingViewOptions;
        /**
          * Aspect ratio used to calculate loader height
         */
        "aspectRatio": number;
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Distance between columns
         */
        "columnGap": string;
        /**
          * Ranking comparable data
         */
        "compRankingData": RankingData[];
        /**
          * Extra i18n translates
         */
        "i18n": { [key: string]: string };
        /**
          * Application interface
         */
        "interface": string;
        /**
          * Loading flag
         */
        "loading": boolean;
        /**
          * Loading comparable flag
         */
        "loadingComparable": boolean;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * Ranking data
         */
        "rankingData": RankingData[];
        /**
          * Distance between rows
         */
        "rowGap": string;
        /**
          * Decorate with backdrop filter, solves some performance issues (in storybook)
         */
        "useBackdropDecoration": boolean;
    }
    interface GlyphScroll {
        /**
          * class name to be used in scroll container
         */
        "containerClass": string;
        /**
          * height property
         */
        "height": number;
        /**
          * hide scrollbar
         */
        "hideScrollBar": boolean;
        /**
          * show horizontal bar
         */
        "horizontal": boolean;
        /**
          * scrollbar initialization callback
         */
        "initCallback": (ps: any) => void;
        /**
          * scrolling speed
         */
        "scrollSpeed": number;
        /**
          * tinyh scrollbar
         */
        "tiny": boolean;
        /**
          * show vertical bar
         */
        "vertical": boolean;
        /**
          * width property
         */
        "width": number;
    }
    interface GlyphSelector {
        /**
          * Complex selector options
         */
        "complexOptions": ComplexSelectorOptions;
        /**
          * Selector disabled state
         */
        "disabled": boolean;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Selector label
         */
        "label": string;
        /**
          * Max height configuration
         */
        "maxHeight": number;
        /**
          * Multiselect flag
         */
        "multiSelect": boolean;
        /**
          * Selector options
         */
        "options": SelectorOption[];
        /**
          * Search placeholder text. If defined a search input will render
         */
        "searchPlaceholder": string;
    }
    interface GlyphSelectorOptions {
        /**
          * Close event
         */
        "closeEvent": () => void;
        /**
          * Complex selector options
         */
        "complexOptions": ComplexSelectorOptions;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Max height configuration
         */
        "maxHeight": number;
        /**
          * Multiselect flag
         */
        "multiSelect": boolean;
        /**
          * Option click event
         */
        "optionClickEvent": (option: SelectorOption) => void;
        /**
          * Selector options
         */
        "options": SelectorOption[];
        /**
          * Search placeholder text. If defined a search input will render
         */
        "searchPlaceholder": string;
    }
    interface GlyphShareMenu {
        /**
          * Application subtitle
         */
        "appSubtitle": string;
        /**
          * Application title
         */
        "appTitle": string;
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback": () => void;
    }
    interface GlyphSkLoader {
        /**
          * Height of loader line
         */
        "height": number;
        /**
          * Number of loader lines that will be rendered
         */
        "repetitions": number;
    }
    interface GlyphSlider {
        /**
          * Current slider value between 0 and 100
         */
        "currentValue": number;
        /**
          * Slider options
         */
        "options": any[];
    }
    interface GlyphSortable {
        /**
          * Child value change
         */
        "childSortCallback": (SortedList: string[]) => any;
        /**
          * [SortableJS](https://github.com/SortableJS/Sortable#options) list configuration
         */
        "config": SortableOptions;
        /**
          * height property (makes list scrollable)
         */
        "height": number;
        /**
          * Children flag
         */
        "isChildren": boolean;
        /**
          * List to sort
         */
        "list": SortableOption[];
        /**
          * Value renderer, if not set list will render `name` property
         */
        "valueGetter": (item: any) => string;
    }
    interface GlyphSortableElement {
        /**
          * Action click callback
         */
        "actionClick": () => any;
        /**
          * Children sort callback
         */
        "childrenSort": (sortedList: string[]) => any;
        /**
          * This variable should be truthy if any element in list renders an icon to align items
         */
        "haveIcon": boolean;
        /**
          * Sortable item configuration
         */
        "item": SortableOption;
        /**
          * Value renderer, if not set list will render `name` property
         */
        "valueGetter": (item: any) => string;
    }
    interface GlyphStyle {
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Theme type
         */
        "theme": string;
    }
    interface GlyphTabs {
        /**
          * Tab rendering style big | small
         */
        "tabStyle": TabStyle;
        /**
          * Component tabs
         */
        "tabs": Tab[];
    }
    interface GlyphTimeline {
        /**
          * Base path to get assets dir
         */
        "basePath": string;
        /**
          * Calendar events
         */
        "calendarEvents": TimelineEvent[];
        /**
          * Events
         */
        "events": TimelineEvent[];
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback": () => void;
    }
    interface GlyphTitle {
        /**
          * interface input
         */
        "interface": string;
        /**
          * title text
         */
        "text": string;
    }
    interface GlyphToaster {
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Id of event that trigger toaster show
         */
        "eventId": string;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * Time to live for shown toaster
         */
        "ttl": number;
    }
    interface GlyphToggler {
        /**
          * Toggler state
         */
        "active": boolean;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
    }
    interface GlyphUserMenu {
        /**
          * Base path to get assets
         */
        "basePath": string;
        /**
          * Show custom config button
         */
        "customConfig": boolean;
        /**
          * Show decimal config flag
         */
        "decimals": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface": string;
        /**
          * Application languages
         */
        "languages": SelectorOption[];
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale": string;
        /**
          * User name
         */
        "name": string;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback": () => void;
        /**
          * Application themes
         */
        "themes": SelectorOption[];
    }
}
declare global {
    interface HTMLGlyphAppMenuElement extends Components.GlyphAppMenu, HTMLStencilElement {
    }
    var HTMLGlyphAppMenuElement: {
        prototype: HTMLGlyphAppMenuElement;
        new (): HTMLGlyphAppMenuElement;
    };
    interface HTMLGlyphArticleElement extends Components.GlyphArticle, HTMLStencilElement {
    }
    var HTMLGlyphArticleElement: {
        prototype: HTMLGlyphArticleElement;
        new (): HTMLGlyphArticleElement;
    };
    interface HTMLGlyphAvatarElement extends Components.GlyphAvatar, HTMLStencilElement {
    }
    var HTMLGlyphAvatarElement: {
        prototype: HTMLGlyphAvatarElement;
        new (): HTMLGlyphAvatarElement;
    };
    interface HTMLGlyphBrandListElement extends Components.GlyphBrandList, HTMLStencilElement {
    }
    var HTMLGlyphBrandListElement: {
        prototype: HTMLGlyphBrandListElement;
        new (): HTMLGlyphBrandListElement;
    };
    interface HTMLGlyphBreadcrumbsElement extends Components.GlyphBreadcrumbs, HTMLStencilElement {
    }
    var HTMLGlyphBreadcrumbsElement: {
        prototype: HTMLGlyphBreadcrumbsElement;
        new (): HTMLGlyphBreadcrumbsElement;
    };
    interface HTMLGlyphButtonElement extends Components.GlyphButton, HTMLStencilElement {
    }
    var HTMLGlyphButtonElement: {
        prototype: HTMLGlyphButtonElement;
        new (): HTMLGlyphButtonElement;
    };
    interface HTMLGlyphButtonGroupElement extends Components.GlyphButtonGroup, HTMLStencilElement {
    }
    var HTMLGlyphButtonGroupElement: {
        prototype: HTMLGlyphButtonGroupElement;
        new (): HTMLGlyphButtonGroupElement;
    };
    interface HTMLGlyphCalendarElement extends Components.GlyphCalendar, HTMLStencilElement {
    }
    var HTMLGlyphCalendarElement: {
        prototype: HTMLGlyphCalendarElement;
        new (): HTMLGlyphCalendarElement;
    };
    interface HTMLGlyphChipsbarElement extends Components.GlyphChipsbar, HTMLStencilElement {
    }
    var HTMLGlyphChipsbarElement: {
        prototype: HTMLGlyphChipsbarElement;
        new (): HTMLGlyphChipsbarElement;
    };
    interface HTMLGlyphConfigModalElement extends Components.GlyphConfigModal, HTMLStencilElement {
    }
    var HTMLGlyphConfigModalElement: {
        prototype: HTMLGlyphConfigModalElement;
        new (): HTMLGlyphConfigModalElement;
    };
    interface HTMLGlyphDateFilterElement extends Components.GlyphDateFilter, HTMLStencilElement {
    }
    var HTMLGlyphDateFilterElement: {
        prototype: HTMLGlyphDateFilterElement;
        new (): HTMLGlyphDateFilterElement;
    };
    interface HTMLGlyphFilterElement extends Components.GlyphFilter, HTMLStencilElement {
    }
    var HTMLGlyphFilterElement: {
        prototype: HTMLGlyphFilterElement;
        new (): HTMLGlyphFilterElement;
    };
    interface HTMLGlyphFilterDrilldownOptionsElement extends Components.GlyphFilterDrilldownOptions, HTMLStencilElement {
    }
    var HTMLGlyphFilterDrilldownOptionsElement: {
        prototype: HTMLGlyphFilterDrilldownOptionsElement;
        new (): HTMLGlyphFilterDrilldownOptionsElement;
    };
    interface HTMLGlyphFilterOptionsElement extends Components.GlyphFilterOptions, HTMLStencilElement {
    }
    var HTMLGlyphFilterOptionsElement: {
        prototype: HTMLGlyphFilterOptionsElement;
        new (): HTMLGlyphFilterOptionsElement;
    };
    interface HTMLGlyphFilterOptionsListElement extends Components.GlyphFilterOptionsList, HTMLStencilElement {
    }
    var HTMLGlyphFilterOptionsListElement: {
        prototype: HTMLGlyphFilterOptionsListElement;
        new (): HTMLGlyphFilterOptionsListElement;
    };
    interface HTMLGlyphFlexElement extends Components.GlyphFlex, HTMLStencilElement {
    }
    var HTMLGlyphFlexElement: {
        prototype: HTMLGlyphFlexElement;
        new (): HTMLGlyphFlexElement;
    };
    interface HTMLGlyphHeaderElement extends Components.GlyphHeader, HTMLStencilElement {
    }
    var HTMLGlyphHeaderElement: {
        prototype: HTMLGlyphHeaderElement;
        new (): HTMLGlyphHeaderElement;
    };
    interface HTMLGlyphIconElement extends Components.GlyphIcon, HTMLStencilElement {
    }
    var HTMLGlyphIconElement: {
        prototype: HTMLGlyphIconElement;
        new (): HTMLGlyphIconElement;
    };
    interface HTMLGlyphInputElement extends Components.GlyphInput, HTMLStencilElement {
    }
    var HTMLGlyphInputElement: {
        prototype: HTMLGlyphInputElement;
        new (): HTMLGlyphInputElement;
    };
    interface HTMLGlyphListElement extends Components.GlyphList, HTMLStencilElement {
    }
    var HTMLGlyphListElement: {
        prototype: HTMLGlyphListElement;
        new (): HTMLGlyphListElement;
    };
    interface HTMLGlyphListRowElement extends Components.GlyphListRow, HTMLStencilElement {
    }
    var HTMLGlyphListRowElement: {
        prototype: HTMLGlyphListRowElement;
        new (): HTMLGlyphListRowElement;
    };
    interface HTMLGlyphLoginElement extends Components.GlyphLogin, HTMLStencilElement {
    }
    var HTMLGlyphLoginElement: {
        prototype: HTMLGlyphLoginElement;
        new (): HTMLGlyphLoginElement;
    };
    interface HTMLGlyphModalElement extends Components.GlyphModal, HTMLStencilElement {
    }
    var HTMLGlyphModalElement: {
        prototype: HTMLGlyphModalElement;
        new (): HTMLGlyphModalElement;
    };
    interface HTMLGlyphNoDataElement extends Components.GlyphNoData, HTMLStencilElement {
    }
    var HTMLGlyphNoDataElement: {
        prototype: HTMLGlyphNoDataElement;
        new (): HTMLGlyphNoDataElement;
    };
    interface HTMLGlyphNotificationsElement extends Components.GlyphNotifications, HTMLStencilElement {
    }
    var HTMLGlyphNotificationsElement: {
        prototype: HTMLGlyphNotificationsElement;
        new (): HTMLGlyphNotificationsElement;
    };
    interface HTMLGlyphPaginationElement extends Components.GlyphPagination, HTMLStencilElement {
    }
    var HTMLGlyphPaginationElement: {
        prototype: HTMLGlyphPaginationElement;
        new (): HTMLGlyphPaginationElement;
    };
    interface HTMLGlyphRankingElement extends Components.GlyphRanking, HTMLStencilElement {
    }
    var HTMLGlyphRankingElement: {
        prototype: HTMLGlyphRankingElement;
        new (): HTMLGlyphRankingElement;
    };
    interface HTMLGlyphRankingLayoutElement extends Components.GlyphRankingLayout, HTMLStencilElement {
    }
    var HTMLGlyphRankingLayoutElement: {
        prototype: HTMLGlyphRankingLayoutElement;
        new (): HTMLGlyphRankingLayoutElement;
    };
    interface HTMLGlyphScrollElement extends Components.GlyphScroll, HTMLStencilElement {
    }
    var HTMLGlyphScrollElement: {
        prototype: HTMLGlyphScrollElement;
        new (): HTMLGlyphScrollElement;
    };
    interface HTMLGlyphSelectorElement extends Components.GlyphSelector, HTMLStencilElement {
    }
    var HTMLGlyphSelectorElement: {
        prototype: HTMLGlyphSelectorElement;
        new (): HTMLGlyphSelectorElement;
    };
    interface HTMLGlyphSelectorOptionsElement extends Components.GlyphSelectorOptions, HTMLStencilElement {
    }
    var HTMLGlyphSelectorOptionsElement: {
        prototype: HTMLGlyphSelectorOptionsElement;
        new (): HTMLGlyphSelectorOptionsElement;
    };
    interface HTMLGlyphShareMenuElement extends Components.GlyphShareMenu, HTMLStencilElement {
    }
    var HTMLGlyphShareMenuElement: {
        prototype: HTMLGlyphShareMenuElement;
        new (): HTMLGlyphShareMenuElement;
    };
    interface HTMLGlyphSkLoaderElement extends Components.GlyphSkLoader, HTMLStencilElement {
    }
    var HTMLGlyphSkLoaderElement: {
        prototype: HTMLGlyphSkLoaderElement;
        new (): HTMLGlyphSkLoaderElement;
    };
    interface HTMLGlyphSliderElement extends Components.GlyphSlider, HTMLStencilElement {
    }
    var HTMLGlyphSliderElement: {
        prototype: HTMLGlyphSliderElement;
        new (): HTMLGlyphSliderElement;
    };
    interface HTMLGlyphSortableElement extends Components.GlyphSortable, HTMLStencilElement {
    }
    var HTMLGlyphSortableElement: {
        prototype: HTMLGlyphSortableElement;
        new (): HTMLGlyphSortableElement;
    };
    interface HTMLGlyphSortableElementElement extends Components.GlyphSortableElement, HTMLStencilElement {
    }
    var HTMLGlyphSortableElementElement: {
        prototype: HTMLGlyphSortableElementElement;
        new (): HTMLGlyphSortableElementElement;
    };
    interface HTMLGlyphStyleElement extends Components.GlyphStyle, HTMLStencilElement {
    }
    var HTMLGlyphStyleElement: {
        prototype: HTMLGlyphStyleElement;
        new (): HTMLGlyphStyleElement;
    };
    interface HTMLGlyphTabsElement extends Components.GlyphTabs, HTMLStencilElement {
    }
    var HTMLGlyphTabsElement: {
        prototype: HTMLGlyphTabsElement;
        new (): HTMLGlyphTabsElement;
    };
    interface HTMLGlyphTimelineElement extends Components.GlyphTimeline, HTMLStencilElement {
    }
    var HTMLGlyphTimelineElement: {
        prototype: HTMLGlyphTimelineElement;
        new (): HTMLGlyphTimelineElement;
    };
    interface HTMLGlyphTitleElement extends Components.GlyphTitle, HTMLStencilElement {
    }
    var HTMLGlyphTitleElement: {
        prototype: HTMLGlyphTitleElement;
        new (): HTMLGlyphTitleElement;
    };
    interface HTMLGlyphToasterElement extends Components.GlyphToaster, HTMLStencilElement {
    }
    var HTMLGlyphToasterElement: {
        prototype: HTMLGlyphToasterElement;
        new (): HTMLGlyphToasterElement;
    };
    interface HTMLGlyphTogglerElement extends Components.GlyphToggler, HTMLStencilElement {
    }
    var HTMLGlyphTogglerElement: {
        prototype: HTMLGlyphTogglerElement;
        new (): HTMLGlyphTogglerElement;
    };
    interface HTMLGlyphUserMenuElement extends Components.GlyphUserMenu, HTMLStencilElement {
    }
    var HTMLGlyphUserMenuElement: {
        prototype: HTMLGlyphUserMenuElement;
        new (): HTMLGlyphUserMenuElement;
    };
    interface HTMLElementTagNameMap {
        "glyph-app-menu": HTMLGlyphAppMenuElement;
        "glyph-article": HTMLGlyphArticleElement;
        "glyph-avatar": HTMLGlyphAvatarElement;
        "glyph-brand-list": HTMLGlyphBrandListElement;
        "glyph-breadcrumbs": HTMLGlyphBreadcrumbsElement;
        "glyph-button": HTMLGlyphButtonElement;
        "glyph-button-group": HTMLGlyphButtonGroupElement;
        "glyph-calendar": HTMLGlyphCalendarElement;
        "glyph-chipsbar": HTMLGlyphChipsbarElement;
        "glyph-config-modal": HTMLGlyphConfigModalElement;
        "glyph-date-filter": HTMLGlyphDateFilterElement;
        "glyph-filter": HTMLGlyphFilterElement;
        "glyph-filter-drilldown-options": HTMLGlyphFilterDrilldownOptionsElement;
        "glyph-filter-options": HTMLGlyphFilterOptionsElement;
        "glyph-filter-options-list": HTMLGlyphFilterOptionsListElement;
        "glyph-flex": HTMLGlyphFlexElement;
        "glyph-header": HTMLGlyphHeaderElement;
        "glyph-icon": HTMLGlyphIconElement;
        "glyph-input": HTMLGlyphInputElement;
        "glyph-list": HTMLGlyphListElement;
        "glyph-list-row": HTMLGlyphListRowElement;
        "glyph-login": HTMLGlyphLoginElement;
        "glyph-modal": HTMLGlyphModalElement;
        "glyph-no-data": HTMLGlyphNoDataElement;
        "glyph-notifications": HTMLGlyphNotificationsElement;
        "glyph-pagination": HTMLGlyphPaginationElement;
        "glyph-ranking": HTMLGlyphRankingElement;
        "glyph-ranking-layout": HTMLGlyphRankingLayoutElement;
        "glyph-scroll": HTMLGlyphScrollElement;
        "glyph-selector": HTMLGlyphSelectorElement;
        "glyph-selector-options": HTMLGlyphSelectorOptionsElement;
        "glyph-share-menu": HTMLGlyphShareMenuElement;
        "glyph-sk-loader": HTMLGlyphSkLoaderElement;
        "glyph-slider": HTMLGlyphSliderElement;
        "glyph-sortable": HTMLGlyphSortableElement;
        "glyph-sortable-element": HTMLGlyphSortableElementElement;
        "glyph-style": HTMLGlyphStyleElement;
        "glyph-tabs": HTMLGlyphTabsElement;
        "glyph-timeline": HTMLGlyphTimelineElement;
        "glyph-title": HTMLGlyphTitleElement;
        "glyph-toaster": HTMLGlyphToasterElement;
        "glyph-toggler": HTMLGlyphTogglerElement;
        "glyph-user-menu": HTMLGlyphUserMenuElement;
    }
}
declare namespace LocalJSX {
    interface GlyphAppMenu {
        /**
          * List of apps
         */
        "apps"?: Screen[];
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Flag to activate search input
         */
        "hasSearch"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback"?: () => void;
    }
    interface GlyphArticle {
        /**
          * Article data
         */
        "article"?: Article;
        /**
          * Aspect ratio used to calculate loader height
         */
        "aspectRatio"?: number;
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Image type to render image | plain_image
         */
        "imageType"?: string;
        /**
          * Flag to activate click callback
         */
        "isClickable"?: boolean;
        /**
          * Force visibility flag
         */
        "isVisible"?: Boolean;
        /**
          * Loading flag
         */
        "loading"?: boolean;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Click event callback
         */
        "onArticleClick"?: (event: CustomEvent<Article>) => void;
        /**
          * Article gets visible event
         */
        "onArticleVisible"?: (event: CustomEvent<any>) => void;
        /**
          * **optional** Compose image url callback
         */
        "parseImageUrl"?: (image: string) => string;
        /**
          * Field to render quantity tag
         */
        "quantityField"?: string;
        /**
          * Decorate with backdrop filter, solves some performance issues (in storybook)
         */
        "useBackdropDecoration"?: boolean;
    }
    interface GlyphAvatar {
        /**
          * User avatar image
         */
        "image"?: UserData['image'];
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * User name, used as image fallback
         */
        "name"?: UserData['name'];
    }
    interface GlyphBrandList {
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Brand list
         */
        "brandList"?: Brand[];
        /**
          * Event triggerd on brand click
         */
        "onBrandChange"?: (event: CustomEvent<Brand>) => void;
        /**
          * Event triggered when user clicks outside
         */
        "outsideCallback"?: () => void;
    }
    interface GlyphBreadcrumbs {
        /**
          * Crumb property. Last one is displayed as active. Each crumb triggers a callback on click
         */
        "crumbs"?: Crumb[];
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
    }
    interface GlyphButton {
        /**
          * Action button. Displayed with text only
         */
        "action"?: boolean;
        /**
          * Cancel type button. Renders in red
         */
        "cancel"?: boolean;
        /**
          * Custom classNames to apply
         */
        "class"?: string;
        /**
          * Material icons id
         */
        "icon"?: string;
        /**
          * Renders icon first
         */
        "iconFirst"?: boolean;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Button text
         */
        "text"?: string;
        /**
          * Tiny action button displays a smaller and thinier text
         */
        "tiny"?: boolean;
    }
    interface GlyphButtonGroup {
        /**
          * Button alignment ['left', 'center', 'right']
         */
        "alignment"?: Alignment;
        /**
          * Buttons configuration
         */
        "buttons"?: Button[];
        /**
          * Application interface
         */
        "interface"?: string;
        /**
          * Button group size ['big', 'small']
         */
        "size"?: ButtonGroupStyle;
    }
    interface GlyphCalendar {
        /**
          * Activate seconday selection display
         */
        "auxActive"?: boolean;
        /**
          * Selected end date
         */
        "endDate"?: Date;
        /**
          * Secondary selected end date
         */
        "endDateAux"?: Date;
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Maximum allowed date
         */
        "maxDate"?: Date;
        /**
          * Maximum allowed date
         */
        "maxDateAux"?: Date;
        /**
          * Minimum allowed date
         */
        "minDate"?: Date;
        /**
          * Minimum allowed date
         */
        "minDateAux"?: Date;
        /**
          * Number of months to be shown. 2 by default
         */
        "months"?: number;
        /**
          * Event triggered on date selection
         */
        "onDateSelect"?: (event: CustomEvent<{ startDate: Date; endDate: Date; comparableType?: ComparableType }>) => void;
        /**
          * Event triggered on aux date selection
         */
        "onDateSelectAux"?: (event: CustomEvent<{ startDate: Date; endDate: Date }>) => void;
        /**
          * Secondary selection. Shows selection in orange. **requires auxActive**
         */
        "secondary"?: boolean;
        /**
          * Allow single day selection
         */
        "singleSelect"?: boolean;
        /**
          * Selected start date
         */
        "startDate"?: Date;
        /**
          * Secondary selected start date
         */
        "startDateAux"?: Date;
    }
    interface GlyphChipsbar {
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Filters configuration object
         */
        "filtersConfig"?: FiltersConfig;
        /**
          * Hide zara south filters active
         */
        "hideZaraSouth"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type
         */
        "interface"?: string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Clear all filters event
         */
        "onClearAll"?: (event: CustomEvent<any>) => void;
        /**
          * Filter clear event
         */
        "onFilterClear"?: (event: CustomEvent<string>) => void;
        /**
          * Filter select event
         */
        "onFilterSelect"?: (event: CustomEvent<FilterSelectEvent>) => void;
        /**
          * Filter multiselect event
         */
        "onUpdateFilter"?: (event: CustomEvent<FilterUpdateEvent>) => void;
    }
    interface GlyphConfigModal {
        /**
          * Filters configuration
         */
        "filtersConfig"?: FiltersConfig;
        /**
          * Hide zara south filters active
         */
        "hideZaraSouth"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type [ 'MODERN', 'CLASSIC' ]
         */
        "interface"?: string;
        /**
          * Filter configuration change event
         */
        "onConfigChange"?: (event: CustomEvent<FiltersConfig>) => void;
    }
    interface GlyphDateFilter {
        /**
          * Active flag
         */
        "active"?: boolean;
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Comparable options
         */
        "comparableOptions"?: SelectorOption[];
        /**
          * Comparabel type
         */
        "comparableType"?: ComparableType;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Maximum available comp date
         */
        "maxComparableDate"?: Date;
        /**
          * Maximum available date
         */
        "maxDate"?: Date;
        /**
          * Minimum available comp date
         */
        "minComparableDate"?: Date;
        /**
          * Minimum available date
         */
        "minDate"?: Date;
        /**
          * Number of months to be shown. 2 by default
         */
        "months"?: number;
        /**
          * Clear selected filters callback
         */
        "onClearEvent"?: (event: CustomEvent<any>) => void;
        /**
          * Date selection event
         */
        "onDateSelection"?: (event: CustomEvent<FilterSelectEvent>) => void;
        /**
          * Filter options
         */
        "options"?: FilterOptionHeader[];
        /**
          * Allow single day selection
         */
        "singleSelect"?: boolean;
    }
    interface GlyphFilter {
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Filter description
         */
        "description"?: string;
        /**
          * Multiselect flag. True if filter allows multiselect toggler
         */
        "haveMultiSelect"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * This flag is true if multiselect is active
         */
        "multiSelect"?: boolean;
        /**
          * Clear selected filters callback
         */
        "onClear"?: (event: CustomEvent<any>) => void;
        /**
          * Multiselect toggler callback
         */
        "onMultiSelectEvent"?: (event: CustomEvent<any>) => void;
        /**
          * Option click event
         */
        "onOptionClick"?: (event: CustomEvent<FilterSelectEvent>) => void;
        /**
          * Filter options
         */
        "options"?: FilterOptionHeader[];
        /**
          * Filter plural
         */
        "plural"?: string;
        /**
          * Search placeholder
         */
        "searchPlaceholder"?: string;
    }
    interface GlyphFilterDrilldownOptions {
        /**
          * Expanded flag
         */
        "expanded"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Filter options
         */
        "option"?: FilterOptionHeader;
        /**
          * Option click event
         */
        "optionClick"?: (option: FilterOptionHeader) => (event: any) => void;
        /**
          * Search value
         */
        "searchValue"?: string;
    }
    interface GlyphFilterOptions {
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Close callback
         */
        "closeEvent"?: () => void;
        /**
          * Filter description
         */
        "description"?: string;
        /**
          * Multiselect flag. True if filter allows multiselect toggler
         */
        "haveMultiSelect"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * This flag is true if multiselect is active
         */
        "multiSelect"?: boolean;
        /**
          * Multiselect toggler callback
         */
        "multiSelectEvent"?: () => void;
        /**
          * Option click event
         */
        "optionClickEvent"?: (option: FilterOptionHeader) => void;
        /**
          * Filter options
         */
        "options"?: FilterOptionHeader[];
        /**
          * Search placeholder
         */
        "searchPlaceholder"?: string;
    }
    interface GlyphFilterOptionsList {
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Style applied in list
         */
        "listStyle"?: { [key: string]: string };
        /**
          * Option click event
         */
        "optionClick"?: (option: FilterOptionHeader) => (event: any) => void;
        /**
          * Filter options
         */
        "options"?: FilterOptionHeader[];
        /**
          * Search value
         */
        "searchValue"?: string;
    }
    interface GlyphFlex {
        /**
          * Apply spaced around distribution
         */
        "around"?: boolean;
        /**
          * Verical align = bottom
         */
        "bottom"?: boolean;
        /**
          * Horizontal align = center
         */
        "center"?: boolean;
        /**
          * Flex-direction = vertical
         */
        "column"?: boolean;
        /**
          * Class attribute to apply in flex div
         */
        "flexClass"?: string;
        /**
          * Id attribute to apply in flex div
         */
        "flexId"?: string;
        /**
          * Style atttribute to apply in flex div
         */
        "flexStyle"?: any;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Horizonal align = left
         */
        "left"?: boolean;
        /**
          * Vertical align = middle
         */
        "middle"?: boolean;
        /**
          * Horizontal align = right
         */
        "right"?: boolean;
        /**
          * Flex-direction = horizontal
         */
        "row"?: boolean;
        /**
          * Apply spaced distribution
         */
        "spaced"?: boolean;
        /**
          * Set an id to attribute data-testid
         */
        "testId"?: string;
        /**
          * Theme type
         */
        "theme"?: UITheme;
        /**
          * Vertical align = top
         */
        "top"?: boolean;
    }
    interface GlyphHeader {
        /**
          * Application brand
         */
        "activeBrand"?: Brands;
        /**
          * Apps data
         */
        "appData"?: Screen[];
        /**
          * Application subtitle
         */
        "appSubtitle"?: string;
        /**
          * Application title
         */
        "appTitle"?: string;
        /**
          * User avatar flag
         */
        "avatar"?: boolean;
        /**
          * Brand selector flag
         */
        "brand"?: boolean;
        /**
          * Available brands list
         */
        "brandList"?: Brand[];
        /**
          * Calendar events
         */
        "calendarEvents"?: TimelineEvent[];
        /**
          * Events
         */
        "events"?: TimelineEvent[];
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * View menu flag
         */
        "menu"?: boolean;
        /**
          * Notification flag
         */
        "notifications"?: boolean;
        /**
          * Brand change event
         */
        "onBrandChange"?: (event: CustomEvent<Brand>) => void;
        /**
          * Custom config change
         */
        "onCustomConfigChange"?: (event: CustomEvent<any>) => void;
        /**
          * Decimals change event
         */
        "onDecimalsChange"?: (event: CustomEvent<boolean>) => void;
        /**
          * Language change event
         */
        "onLangChange"?: (event: CustomEvent<SelectorOption>) => void;
        /**
          * Logout event
         */
        "onLogout"?: (event: CustomEvent<any>) => void;
        /**
          * Theme change event
         */
        "onThemeChange"?: (event: CustomEvent<SelectorOption>) => void;
        /**
          * Search flag
         */
        "search"?: boolean;
        /**
          * Share menu flag
         */
        "share"?: boolean;
        /**
          * Timeline flag
         */
        "timeline"?: boolean;
        /**
          * User data
         */
        "userData"?: UserData;
        /**
          * User menu config
         */
        "userMenuConfig"?: UserMenuConfiguration;
    }
    interface GlyphIcon {
        /**
          * render icon with button role
         */
        "button"?: boolean;
        /**
          * class to use in icon
         */
        "class"?: string;
        /**
          * click callback
         */
        "clickCbk"?: (event: MouseEvent) => any;
        /**
          * icon name
         */
        "icon"?: string;
        /**
          * render material icon
         */
        "material"?: boolean;
        /**
          * render outlined icon (for material icons)
         */
        "outlined"?: boolean;
    }
    interface GlyphInput {
        /**
          * Input should auto focus
         */
        "autoFocus"?: boolean;
        /**
          * Renders input in a box
         */
        "box"?: boolean;
        /**
          * Flag to disable input
         */
        "disabled"?: boolean;
        /**
          * Style input as an error
         */
        "error"?: boolean;
        /**
          * Input type
         */
        "inputType"?: string;
        /**
          * Filter chip interface ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Maximum availabla for inputs (dates or ranges)
         */
        "max"?: any;
        /**
          * Minimum available for inputs (dates or ranges)
         */
        "min"?: any;
        /**
          * Enter key event
         */
        "onEnterKey"?: (event: CustomEvent<any>) => void;
        /**
          * Text change event
         */
        "onInputChange"?: (event: CustomEvent<string>) => void;
        /**
          * Placeholder
         */
        "placeholder"?: string;
        /**
          * Search flag, renders a search icon if `box` is false
         */
        "search"?: boolean;
        /**
          * Input value
         */
        "value"?: any;
    }
    interface GlyphList {
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Component data. Fields preffixed with `_` will not render
         */
        "data"?: Row[];
        /**
          * Show decimals flag
         */
        "decimals"?: boolean;
        /**
          * Default sorting field, it could be a private or public field
         */
        "defaultSortField"?: string;
        /**
          * Enable download xlsx file
         */
        "enableDownload"?: boolean;
        /**
          * Expandable flag
         */
        "expandable"?: boolean;
        /**
          * Rows that has no data on these fields will not render
         */
        "filterFields"?: string[];
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Rows limit. If not set will take `16` as default value or `10` in small screens
         */
        "limit"?: number;
        /**
          * Loading state. If true will render skeleton loader
         */
        "loading"?: boolean;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Expand row event
         */
        "onExpandRow"?: (event: CustomEvent<Row>) => void;
        /**
          * Number of pages to be grouped if list is larger than limit
         */
        "pageGroups"?: number;
        /**
          * Pagination limit
         */
        "paginationLimit"?: number;
        /**
          * Force component update if flag is true
         */
        "update"?: boolean;
    }
    interface GlyphListRow {
        /**
          * expand row callback
         */
        "expandHandle"?: (row: Row) => () => any;
        /**
          * expandable flag
         */
        "expandable"?: boolean;
        /**
          * Render fields
         */
        "fields"?: string[];
        /**
          * i18n object with translations
         */
        "i18n"?: any;
        /**
          * total flag
         */
        "isTotal"?: boolean;
        /**
          * row data
         */
        "row"?: Row;
    }
    interface GlyphLogin {
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Extra i18n translates
         */
        "i18n"?: { [key: string]: string };
        /**
          * Component interface *modern* | *classic*
         */
        "interface"?: string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Login callback
         */
        "login"?: (userData: { user: string; password: string }) => void;
        /**
          * On login success
         */
        "loginSuccess"?: (result: any) => void;
        /**
          * Application version
         */
        "version"?: string;
    }
    interface GlyphModal {
        /**
          * Apply button text. Renders button if set
         */
        "applyButton"?: string;
        /**
          * Cancel button text. Renders button if set
         */
        "cancelButton"?: string;
        /**
          * Close button flag
         */
        "closeButton"?: boolean;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Modal min height
         */
        "maxHeight"?: string;
        /**
          * Modal min with
         */
        "maxWidth"?: string;
        /**
          * Modal title
         */
        "modalTitle"?: string;
        /**
          * apply event
         */
        "onApply"?: (event: CustomEvent<any>) => void;
        /**
          * cancel event
         */
        "onCancel"?: (event: CustomEvent<any>) => void;
        /**
          * close event
         */
        "onClose"?: (event: CustomEvent<any>) => void;
        /**
          * Modal padded flag
         */
        "padded"?: boolean;
        /**
          * Modal visibility flag
         */
        "visible"?: boolean;
    }
    interface GlyphNoData {
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Bottom text. only applies if render mode is advanced
         */
        "bottomText"?: string;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Render mode [ 'simple' | 'complex' ]
         */
        "mode"?: string;
        /**
          * Top text only applies if render mode is advanced
         */
        "text"?: string;
    }
    interface GlyphNotifications {
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback"?: () => void;
    }
    interface GlyphPagination {
        /**
          * Active page
         */
        "activePage"?: number;
        /**
          * Pagination limit in first group
         */
        "limit"?: number;
        /**
          * Event emitted on page click
         */
        "onSetPage"?: (event: CustomEvent<number>) => void;
        /**
          * Number of pages to be grouped if list is larger than limit
         */
        "pageGroups"?: number;
        /**
          * Number of pages to be rendered
         */
        "pages"?: number;
    }
    interface GlyphRanking {
        /**
          * Aspect ratio used to calculate loader height
         */
        "aspectRatio"?: number;
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Distance between columns
         */
        "columnGap"?: string;
        /**
          * Columns to render if ranking have more than 1 section, number of columns will apply per section
         */
        "columns"?: number;
        /**
          * Distance applied to both axes
         */
        "gap"?: string;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Image type to render image | plain_image
         */
        "imageType"?: string;
        /**
          * Inner columns, sets how many columns should be rendered per column
         */
        "innerColumns"?: number;
        /**
          * Distance between elements inside a column
         */
        "innerGap"?: string;
        /**
          * Loading flag
         */
        "loading"?: boolean;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Scrolled state change event
         */
        "onScrollChange"?: (event: CustomEvent<{ scrolled: boolean; scrollTop: number }>) => void;
        /**
          * **optional** Compose image url callback
         */
        "parseImageUrl"?: (image: string) => string;
        /**
          * Ranking data
         */
        "rankingData"?: RankingData[];
        /**
          * (optional) ranking header. Applicable on single section ranking
         */
        "rankingHeader"?: string;
        /**
          * Distance between rows
         */
        "rowGap"?: string;
        /**
          * Row to render
         */
        "rows"?: number;
        /**
          * Decorate with backdrop filter, solves some performance issues (in storybook)
         */
        "useBackdropDecoration"?: boolean;
    }
    interface GlyphRankingLayout {
        /**
          * Active view layout
         */
        "activeView"?: RankingViewOptions;
        /**
          * Aspect ratio used to calculate loader height
         */
        "aspectRatio"?: number;
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Distance between columns
         */
        "columnGap"?: string;
        /**
          * Ranking comparable data
         */
        "compRankingData"?: RankingData[];
        /**
          * Extra i18n translates
         */
        "i18n"?: { [key: string]: string };
        /**
          * Application interface
         */
        "interface"?: string;
        /**
          * Loading flag
         */
        "loading"?: boolean;
        /**
          * Loading comparable flag
         */
        "loadingComparable"?: boolean;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Ranking data
         */
        "rankingData"?: RankingData[];
        /**
          * Distance between rows
         */
        "rowGap"?: string;
        /**
          * Decorate with backdrop filter, solves some performance issues (in storybook)
         */
        "useBackdropDecoration"?: boolean;
    }
    interface GlyphScroll {
        /**
          * class name to be used in scroll container
         */
        "containerClass"?: string;
        /**
          * height property
         */
        "height"?: number;
        /**
          * hide scrollbar
         */
        "hideScrollBar"?: boolean;
        /**
          * show horizontal bar
         */
        "horizontal"?: boolean;
        /**
          * scrollbar initialization callback
         */
        "initCallback"?: (ps: any) => void;
        /**
          * scrolling speed
         */
        "scrollSpeed"?: number;
        /**
          * tinyh scrollbar
         */
        "tiny"?: boolean;
        /**
          * show vertical bar
         */
        "vertical"?: boolean;
        /**
          * width property
         */
        "width"?: number;
    }
    interface GlyphSelector {
        /**
          * Complex selector options
         */
        "complexOptions"?: ComplexSelectorOptions;
        /**
          * Selector disabled state
         */
        "disabled"?: boolean;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Selector label
         */
        "label"?: string;
        /**
          * Max height configuration
         */
        "maxHeight"?: number;
        /**
          * Multiselect flag
         */
        "multiSelect"?: boolean;
        /**
          * on change callback
         */
        "onOptionSelect"?: (event: CustomEvent<SelectorOption>) => void;
        /**
          * Selector options
         */
        "options"?: SelectorOption[];
        /**
          * Search placeholder text. If defined a search input will render
         */
        "searchPlaceholder"?: string;
    }
    interface GlyphSelectorOptions {
        /**
          * Close event
         */
        "closeEvent"?: () => void;
        /**
          * Complex selector options
         */
        "complexOptions"?: ComplexSelectorOptions;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Max height configuration
         */
        "maxHeight"?: number;
        /**
          * Multiselect flag
         */
        "multiSelect"?: boolean;
        /**
          * Option click event
         */
        "optionClickEvent"?: (option: SelectorOption) => void;
        /**
          * Selector options
         */
        "options"?: SelectorOption[];
        /**
          * Search placeholder text. If defined a search input will render
         */
        "searchPlaceholder"?: string;
    }
    interface GlyphShareMenu {
        /**
          * Application subtitle
         */
        "appSubtitle"?: string;
        /**
          * Application title
         */
        "appTitle"?: string;
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback"?: () => void;
    }
    interface GlyphSkLoader {
        /**
          * Height of loader line
         */
        "height"?: number;
        /**
          * Number of loader lines that will be rendered
         */
        "repetitions"?: number;
    }
    interface GlyphSlider {
        /**
          * Current slider value between 0 and 100
         */
        "currentValue"?: number;
        /**
          * Option change event
         */
        "onOptionChange"?: (event: CustomEvent<{ option: any; value: number }>) => void;
        /**
          * Slider options
         */
        "options"?: any[];
    }
    interface GlyphSortable {
        /**
          * Child value change
         */
        "childSortCallback"?: (SortedList: string[]) => any;
        /**
          * [SortableJS](https://github.com/SortableJS/Sortable#options) list configuration
         */
        "config"?: SortableOptions;
        /**
          * height property (makes list scrollable)
         */
        "height"?: number;
        /**
          * Children flag
         */
        "isChildren"?: boolean;
        /**
          * List to sort
         */
        "list"?: SortableOption[];
        /**
          * Event emitted on drag end emitting new list configuration
         */
        "onAdd"?: (event: CustomEvent<string[]>) => void;
        /**
          * Event emitted on drag end emitting new list configuration
         */
        "onChildrenSortChange"?: (event: CustomEvent<SortableChildrenEvent>) => void;
        /**
          * Event emitted on drag end emitting new list configuration
         */
        "onRemove"?: (event: CustomEvent<string[]>) => void;
        /**
          * Event emitted on drag end emitting new list configuration
         */
        "onSortChange"?: (event: CustomEvent<string[]>) => void;
        /**
          * Value renderer, if not set list will render `name` property
         */
        "valueGetter"?: (item: any) => string;
    }
    interface GlyphSortableElement {
        /**
          * Action click callback
         */
        "actionClick"?: () => any;
        /**
          * Children sort callback
         */
        "childrenSort"?: (sortedList: string[]) => any;
        /**
          * This variable should be truthy if any element in list renders an icon to align items
         */
        "haveIcon"?: boolean;
        /**
          * Sortable item configuration
         */
        "item"?: SortableOption;
        /**
          * Value renderer, if not set list will render `name` property
         */
        "valueGetter"?: (item: any) => string;
    }
    interface GlyphStyle {
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Theme type
         */
        "theme"?: string;
    }
    interface GlyphTabs {
        /**
          * Tab selection event
         */
        "onTabSelect"?: (event: CustomEvent<Tab>) => void;
        /**
          * Tab rendering style big | small
         */
        "tabStyle"?: TabStyle;
        /**
          * Component tabs
         */
        "tabs"?: Tab[];
    }
    interface GlyphTimeline {
        /**
          * Base path to get assets dir
         */
        "basePath"?: string;
        /**
          * Calendar events
         */
        "calendarEvents"?: TimelineEvent[];
        /**
          * Events
         */
        "events"?: TimelineEvent[];
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback"?: () => void;
    }
    interface GlyphTitle {
        /**
          * interface input
         */
        "interface"?: string;
        /**
          * title text
         */
        "text"?: string;
    }
    interface GlyphToaster {
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Id of event that trigger toaster show
         */
        "eventId"?: string;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * Time to live for shown toaster
         */
        "ttl"?: number;
    }
    interface GlyphToggler {
        /**
          * Toggler state
         */
        "active"?: boolean;
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
    }
    interface GlyphUserMenu {
        /**
          * Base path to get assets
         */
        "basePath"?: string;
        /**
          * Show custom config button
         */
        "customConfig"?: boolean;
        /**
          * Show decimal config flag
         */
        "decimals"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Interface type ['MODERN', 'CLASSIC']
         */
        "interface"?: string;
        /**
          * Application languages
         */
        "languages"?: SelectorOption[];
        /**
          * **optional** force locale change if html lang is not interpreted
         */
        "locale"?: string;
        /**
          * User name
         */
        "name"?: string;
        /**
          * Custom config event
         */
        "onCustomConfigChange"?: (event: CustomEvent<any>) => void;
        /**
          * Decimals change event
         */
        "onDecimalsChange"?: (event: CustomEvent<boolean>) => void;
        /**
          * Language change event
         */
        "onLangChange"?: (event: CustomEvent<SelectorOption>) => void;
        /**
          * Logout event, trigger an event identified with **logout** key
         */
        "onLogout"?: (event: CustomEvent<any>) => void;
        /**
          * Theme change event
         */
        "onThemeChange"?: (event: CustomEvent<SelectorOption>) => void;
        /**
          * Event triggered when user clicks outside component container
         */
        "outsideCallback"?: () => void;
        /**
          * Application themes
         */
        "themes"?: SelectorOption[];
    }
    interface IntrinsicElements {
        "glyph-app-menu": GlyphAppMenu;
        "glyph-article": GlyphArticle;
        "glyph-avatar": GlyphAvatar;
        "glyph-brand-list": GlyphBrandList;
        "glyph-breadcrumbs": GlyphBreadcrumbs;
        "glyph-button": GlyphButton;
        "glyph-button-group": GlyphButtonGroup;
        "glyph-calendar": GlyphCalendar;
        "glyph-chipsbar": GlyphChipsbar;
        "glyph-config-modal": GlyphConfigModal;
        "glyph-date-filter": GlyphDateFilter;
        "glyph-filter": GlyphFilter;
        "glyph-filter-drilldown-options": GlyphFilterDrilldownOptions;
        "glyph-filter-options": GlyphFilterOptions;
        "glyph-filter-options-list": GlyphFilterOptionsList;
        "glyph-flex": GlyphFlex;
        "glyph-header": GlyphHeader;
        "glyph-icon": GlyphIcon;
        "glyph-input": GlyphInput;
        "glyph-list": GlyphList;
        "glyph-list-row": GlyphListRow;
        "glyph-login": GlyphLogin;
        "glyph-modal": GlyphModal;
        "glyph-no-data": GlyphNoData;
        "glyph-notifications": GlyphNotifications;
        "glyph-pagination": GlyphPagination;
        "glyph-ranking": GlyphRanking;
        "glyph-ranking-layout": GlyphRankingLayout;
        "glyph-scroll": GlyphScroll;
        "glyph-selector": GlyphSelector;
        "glyph-selector-options": GlyphSelectorOptions;
        "glyph-share-menu": GlyphShareMenu;
        "glyph-sk-loader": GlyphSkLoader;
        "glyph-slider": GlyphSlider;
        "glyph-sortable": GlyphSortable;
        "glyph-sortable-element": GlyphSortableElement;
        "glyph-style": GlyphStyle;
        "glyph-tabs": GlyphTabs;
        "glyph-timeline": GlyphTimeline;
        "glyph-title": GlyphTitle;
        "glyph-toaster": GlyphToaster;
        "glyph-toggler": GlyphToggler;
        "glyph-user-menu": GlyphUserMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "glyph-app-menu": LocalJSX.GlyphAppMenu & JSXBase.HTMLAttributes<HTMLGlyphAppMenuElement>;
            "glyph-article": LocalJSX.GlyphArticle & JSXBase.HTMLAttributes<HTMLGlyphArticleElement>;
            "glyph-avatar": LocalJSX.GlyphAvatar & JSXBase.HTMLAttributes<HTMLGlyphAvatarElement>;
            "glyph-brand-list": LocalJSX.GlyphBrandList & JSXBase.HTMLAttributes<HTMLGlyphBrandListElement>;
            "glyph-breadcrumbs": LocalJSX.GlyphBreadcrumbs & JSXBase.HTMLAttributes<HTMLGlyphBreadcrumbsElement>;
            "glyph-button": LocalJSX.GlyphButton & JSXBase.HTMLAttributes<HTMLGlyphButtonElement>;
            "glyph-button-group": LocalJSX.GlyphButtonGroup & JSXBase.HTMLAttributes<HTMLGlyphButtonGroupElement>;
            "glyph-calendar": LocalJSX.GlyphCalendar & JSXBase.HTMLAttributes<HTMLGlyphCalendarElement>;
            "glyph-chipsbar": LocalJSX.GlyphChipsbar & JSXBase.HTMLAttributes<HTMLGlyphChipsbarElement>;
            "glyph-config-modal": LocalJSX.GlyphConfigModal & JSXBase.HTMLAttributes<HTMLGlyphConfigModalElement>;
            "glyph-date-filter": LocalJSX.GlyphDateFilter & JSXBase.HTMLAttributes<HTMLGlyphDateFilterElement>;
            "glyph-filter": LocalJSX.GlyphFilter & JSXBase.HTMLAttributes<HTMLGlyphFilterElement>;
            "glyph-filter-drilldown-options": LocalJSX.GlyphFilterDrilldownOptions & JSXBase.HTMLAttributes<HTMLGlyphFilterDrilldownOptionsElement>;
            "glyph-filter-options": LocalJSX.GlyphFilterOptions & JSXBase.HTMLAttributes<HTMLGlyphFilterOptionsElement>;
            "glyph-filter-options-list": LocalJSX.GlyphFilterOptionsList & JSXBase.HTMLAttributes<HTMLGlyphFilterOptionsListElement>;
            "glyph-flex": LocalJSX.GlyphFlex & JSXBase.HTMLAttributes<HTMLGlyphFlexElement>;
            "glyph-header": LocalJSX.GlyphHeader & JSXBase.HTMLAttributes<HTMLGlyphHeaderElement>;
            "glyph-icon": LocalJSX.GlyphIcon & JSXBase.HTMLAttributes<HTMLGlyphIconElement>;
            "glyph-input": LocalJSX.GlyphInput & JSXBase.HTMLAttributes<HTMLGlyphInputElement>;
            "glyph-list": LocalJSX.GlyphList & JSXBase.HTMLAttributes<HTMLGlyphListElement>;
            "glyph-list-row": LocalJSX.GlyphListRow & JSXBase.HTMLAttributes<HTMLGlyphListRowElement>;
            "glyph-login": LocalJSX.GlyphLogin & JSXBase.HTMLAttributes<HTMLGlyphLoginElement>;
            "glyph-modal": LocalJSX.GlyphModal & JSXBase.HTMLAttributes<HTMLGlyphModalElement>;
            "glyph-no-data": LocalJSX.GlyphNoData & JSXBase.HTMLAttributes<HTMLGlyphNoDataElement>;
            "glyph-notifications": LocalJSX.GlyphNotifications & JSXBase.HTMLAttributes<HTMLGlyphNotificationsElement>;
            "glyph-pagination": LocalJSX.GlyphPagination & JSXBase.HTMLAttributes<HTMLGlyphPaginationElement>;
            "glyph-ranking": LocalJSX.GlyphRanking & JSXBase.HTMLAttributes<HTMLGlyphRankingElement>;
            "glyph-ranking-layout": LocalJSX.GlyphRankingLayout & JSXBase.HTMLAttributes<HTMLGlyphRankingLayoutElement>;
            "glyph-scroll": LocalJSX.GlyphScroll & JSXBase.HTMLAttributes<HTMLGlyphScrollElement>;
            "glyph-selector": LocalJSX.GlyphSelector & JSXBase.HTMLAttributes<HTMLGlyphSelectorElement>;
            "glyph-selector-options": LocalJSX.GlyphSelectorOptions & JSXBase.HTMLAttributes<HTMLGlyphSelectorOptionsElement>;
            "glyph-share-menu": LocalJSX.GlyphShareMenu & JSXBase.HTMLAttributes<HTMLGlyphShareMenuElement>;
            "glyph-sk-loader": LocalJSX.GlyphSkLoader & JSXBase.HTMLAttributes<HTMLGlyphSkLoaderElement>;
            "glyph-slider": LocalJSX.GlyphSlider & JSXBase.HTMLAttributes<HTMLGlyphSliderElement>;
            "glyph-sortable": LocalJSX.GlyphSortable & JSXBase.HTMLAttributes<HTMLGlyphSortableElement>;
            "glyph-sortable-element": LocalJSX.GlyphSortableElement & JSXBase.HTMLAttributes<HTMLGlyphSortableElementElement>;
            "glyph-style": LocalJSX.GlyphStyle & JSXBase.HTMLAttributes<HTMLGlyphStyleElement>;
            "glyph-tabs": LocalJSX.GlyphTabs & JSXBase.HTMLAttributes<HTMLGlyphTabsElement>;
            "glyph-timeline": LocalJSX.GlyphTimeline & JSXBase.HTMLAttributes<HTMLGlyphTimelineElement>;
            "glyph-title": LocalJSX.GlyphTitle & JSXBase.HTMLAttributes<HTMLGlyphTitleElement>;
            "glyph-toaster": LocalJSX.GlyphToaster & JSXBase.HTMLAttributes<HTMLGlyphToasterElement>;
            "glyph-toggler": LocalJSX.GlyphToggler & JSXBase.HTMLAttributes<HTMLGlyphTogglerElement>;
            "glyph-user-menu": LocalJSX.GlyphUserMenu & JSXBase.HTMLAttributes<HTMLGlyphUserMenuElement>;
        }
    }
}
