/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { FilterOptionHeader, FiltersConfig, Row, SelectedFilter } from 'glyph-core';
import { ExpandRowEvent } from './components/list/list.model';
export namespace Components {
    interface GlyphButton {
        /**
         * Material icons id
         */
        icon: string;
        /**
         * Button text
         */
        text: string;
    }
    interface GlyphChipsbar {
        /**
         * Filters configuration object
         */
        filtersConfig: FiltersConfig;
        /**
         * Extra i18n translation object
         */
        i18n: { [key: string]: string };
    }
    interface GlyphFilter {
        /**
         * Filter description
         */
        description: string;
        /**
         * Multiselect flag. True if filter allows multiselect toggler
         */
        haveMultiSelect: boolean;
        /**
         * Extra i18n translation object
         */
        i18n: { [key: string]: string };
        /**
         * This flag is true if multiselect is active
         */
        multiSelect: boolean;
        /**
         * Filter options
         */
        options: FilterOptionHeader[];
        /**
         * Filter plural
         */
        plural: string;
        /**
         * Search placeholder
         */
        searchPlaceholder: string;
        /**
         * Filter selected
         */
        selected: SelectedFilter[];
    }
    interface GlyphList {
        /**
         * Component data. Fields preffixed with `_` will not render
         */
        data: Row[];
        /**
         * Show decimals flag
         */
        decimals: boolean;
        /**
         * Default sorting field, it could be a private or public field
         */
        defaultSortField: string;
        /**
         * Enable download xlsx file
         */
        enableDownload: boolean;
        /**
         * Expandable flag
         */
        expandable: boolean;
        /**
         * Rows that has no data on these fields will not render
         */
        filterFields: string[];
        /**
         * Extra i18n translation object
         */
        i18n: { [key: string]: string };
        /**
         * Rows limit. If not set will take `16` as default value or `10` in small screens
         */
        limit: number;
        /**
         * Loading state. If true will render skeleton loader
         */
        loading: boolean;
        /**
         * Force component update if flag is true
         */
        update: boolean;
    }
    interface GlyphListRow {
        /**
         * expand row callback
         */
        expandHandle: (row: Row) => () => any;
        /**
         * expandable flag
         */
        expandable: boolean;
        /**
         * Render fields
         */
        fields: string[];
        /**
         * i18n object with translations
         */
        i18n: any;
        /**
         * total flag
         */
        isTotal: boolean;
        /**
         * row data
         */
        row: Row;
    }
    interface GlyphNoData {
        /**
         * Bottom text. only applies if render mode is advanced
         */
        bottomText: string;
        /**
         * Extra i18n translation object
         */
        i18n: { [key: string]: string };
        /**
         * Render mode [ 'simple' | 'complex' ]
         */
        mode: string;
        /**
         * Top text only applies if render mode is advanced
         */
        text: string;
    }
    interface GlyphSkLoader {
        /**
         * Height of loader line
         */
        height: number;
        /**
         * Number of loader lines that will be rendered
         */
        repetitions: number;
    }
    interface GlyphTitle {
        /**
         * title text
         */
        titleText: string;
    }
    interface GlyphToggler {
        /**
         * Toggler state
         */
        active: boolean;
        /**
         * Click callback
         */
        callback: () => any;
    }
}
declare global {
    interface HTMLGlyphButtonElement extends Components.GlyphButton, HTMLStencilElement {}
    var HTMLGlyphButtonElement: {
        prototype: HTMLGlyphButtonElement;
        new (): HTMLGlyphButtonElement;
    };
    interface HTMLGlyphChipsbarElement extends Components.GlyphChipsbar, HTMLStencilElement {}
    var HTMLGlyphChipsbarElement: {
        prototype: HTMLGlyphChipsbarElement;
        new (): HTMLGlyphChipsbarElement;
    };
    interface HTMLGlyphFilterElement extends Components.GlyphFilter, HTMLStencilElement {}
    var HTMLGlyphFilterElement: {
        prototype: HTMLGlyphFilterElement;
        new (): HTMLGlyphFilterElement;
    };
    interface HTMLGlyphListElement extends Components.GlyphList, HTMLStencilElement {}
    var HTMLGlyphListElement: {
        prototype: HTMLGlyphListElement;
        new (): HTMLGlyphListElement;
    };
    interface HTMLGlyphListRowElement extends Components.GlyphListRow, HTMLStencilElement {}
    var HTMLGlyphListRowElement: {
        prototype: HTMLGlyphListRowElement;
        new (): HTMLGlyphListRowElement;
    };
    interface HTMLGlyphNoDataElement extends Components.GlyphNoData, HTMLStencilElement {}
    var HTMLGlyphNoDataElement: {
        prototype: HTMLGlyphNoDataElement;
        new (): HTMLGlyphNoDataElement;
    };
    interface HTMLGlyphSkLoaderElement extends Components.GlyphSkLoader, HTMLStencilElement {}
    var HTMLGlyphSkLoaderElement: {
        prototype: HTMLGlyphSkLoaderElement;
        new (): HTMLGlyphSkLoaderElement;
    };
    interface HTMLGlyphTitleElement extends Components.GlyphTitle, HTMLStencilElement {}
    var HTMLGlyphTitleElement: {
        prototype: HTMLGlyphTitleElement;
        new (): HTMLGlyphTitleElement;
    };
    interface HTMLGlyphTogglerElement extends Components.GlyphToggler, HTMLStencilElement {}
    var HTMLGlyphTogglerElement: {
        prototype: HTMLGlyphTogglerElement;
        new (): HTMLGlyphTogglerElement;
    };
    interface HTMLElementTagNameMap {
        'glyph-button': HTMLGlyphButtonElement;
        'glyph-chipsbar': HTMLGlyphChipsbarElement;
        'glyph-filter': HTMLGlyphFilterElement;
        'glyph-list': HTMLGlyphListElement;
        'glyph-list-row': HTMLGlyphListRowElement;
        'glyph-no-data': HTMLGlyphNoDataElement;
        'glyph-sk-loader': HTMLGlyphSkLoaderElement;
        'glyph-title': HTMLGlyphTitleElement;
        'glyph-toggler': HTMLGlyphTogglerElement;
    }
}
declare namespace LocalJSX {
    interface GlyphButton {
        /**
         * Material icons id
         */
        icon?: string;
        /**
         * Button text
         */
        text?: string;
    }
    interface GlyphChipsbar {
        /**
         * Filters configuration object
         */
        filtersConfig?: FiltersConfig;
        /**
         * Extra i18n translation object
         */
        i18n?: { [key: string]: string };
        /**
         * Clear all filters event
         */
        onClearAll?: (event: CustomEvent<any>) => void;
        /**
         * Filter clear event
         */
        onFilterClear?: (event: CustomEvent<any>) => void;
        /**
         * Filter multiselect event
         */
        onFilterMultiSelect?: (event: CustomEvent<any>) => void;
        /**
         * Filter select event
         */
        onFilterSelect?: (event: CustomEvent<any>) => void;
    }
    interface GlyphFilter {
        /**
         * Filter description
         */
        description?: string;
        /**
         * Multiselect flag. True if filter allows multiselect toggler
         */
        haveMultiSelect?: boolean;
        /**
         * Extra i18n translation object
         */
        i18n?: { [key: string]: string };
        /**
         * This flag is true if multiselect is active
         */
        multiSelect?: boolean;
        /**
         * Clear selected filters callback
         */
        onClearEvent?: (event: CustomEvent<any>) => void;
        /**
         * Multiselect toggler callback
         */
        onMultiSelectEvent?: (event: CustomEvent<any>) => void;
        /**
         * Option click event
         */
        onOptionClickEvent?: (event: CustomEvent<any>) => void;
        /**
         * Filter options
         */
        options?: FilterOptionHeader[];
        /**
         * Filter plural
         */
        plural?: string;
        /**
         * Search placeholder
         */
        searchPlaceholder?: string;
        /**
         * Filter selected
         */
        selected?: SelectedFilter[];
    }
    interface GlyphList {
        /**
         * Component data. Fields preffixed with `_` will not render
         */
        data?: Row[];
        /**
         * Show decimals flag
         */
        decimals?: boolean;
        /**
         * Default sorting field, it could be a private or public field
         */
        defaultSortField?: string;
        /**
         * Enable download xlsx file
         */
        enableDownload?: boolean;
        /**
         * Expandable flag
         */
        expandable?: boolean;
        /**
         * Rows that has no data on these fields will not render
         */
        filterFields?: string[];
        /**
         * Extra i18n translation object
         */
        i18n?: { [key: string]: string };
        /**
         * Rows limit. If not set will take `16` as default value or `10` in small screens
         */
        limit?: number;
        /**
         * Loading state. If true will render skeleton loader
         */
        loading?: boolean;
        /**
         * Expand row event
         */
        onExpandRow?: (event: CustomEvent<ExpandRowEvent>) => void;
        /**
         * Force component update if flag is true
         */
        update?: boolean;
    }
    interface GlyphListRow {
        /**
         * expand row callback
         */
        expandHandle?: (row: Row) => () => any;
        /**
         * expandable flag
         */
        expandable?: boolean;
        /**
         * Render fields
         */
        fields?: string[];
        /**
         * i18n object with translations
         */
        i18n?: any;
        /**
         * total flag
         */
        isTotal?: boolean;
        /**
         * row data
         */
        row?: Row;
    }
    interface GlyphNoData {
        /**
         * Bottom text. only applies if render mode is advanced
         */
        bottomText?: string;
        /**
         * Extra i18n translation object
         */
        i18n?: { [key: string]: string };
        /**
         * Render mode [ 'simple' | 'complex' ]
         */
        mode?: string;
        /**
         * Top text only applies if render mode is advanced
         */
        text?: string;
    }
    interface GlyphSkLoader {
        /**
         * Height of loader line
         */
        height?: number;
        /**
         * Number of loader lines that will be rendered
         */
        repetitions?: number;
    }
    interface GlyphTitle {
        /**
         * title text
         */
        titleText?: string;
    }
    interface GlyphToggler {
        /**
         * Toggler state
         */
        active?: boolean;
        /**
         * Click callback
         */
        callback?: () => any;
    }
    interface IntrinsicElements {
        'glyph-button': GlyphButton;
        'glyph-chipsbar': GlyphChipsbar;
        'glyph-filter': GlyphFilter;
        'glyph-list': GlyphList;
        'glyph-list-row': GlyphListRow;
        'glyph-no-data': GlyphNoData;
        'glyph-sk-loader': GlyphSkLoader;
        'glyph-title': GlyphTitle;
        'glyph-toggler': GlyphToggler;
    }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
    export namespace JSX {
        interface IntrinsicElements {
            'glyph-button': LocalJSX.GlyphButton & JSXBase.HTMLAttributes<HTMLGlyphButtonElement>;
            'glyph-chipsbar': LocalJSX.GlyphChipsbar & JSXBase.HTMLAttributes<HTMLGlyphChipsbarElement>;
            'glyph-filter': LocalJSX.GlyphFilter & JSXBase.HTMLAttributes<HTMLGlyphFilterElement>;
            'glyph-list': LocalJSX.GlyphList & JSXBase.HTMLAttributes<HTMLGlyphListElement>;
            'glyph-list-row': LocalJSX.GlyphListRow & JSXBase.HTMLAttributes<HTMLGlyphListRowElement>;
            'glyph-no-data': LocalJSX.GlyphNoData & JSXBase.HTMLAttributes<HTMLGlyphNoDataElement>;
            'glyph-sk-loader': LocalJSX.GlyphSkLoader & JSXBase.HTMLAttributes<HTMLGlyphSkLoaderElement>;
            'glyph-title': LocalJSX.GlyphTitle & JSXBase.HTMLAttributes<HTMLGlyphTitleElement>;
            'glyph-toggler': LocalJSX.GlyphToggler & JSXBase.HTMLAttributes<HTMLGlyphTogglerElement>;
        }
    }
}
