/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FieldsConfig, Row } from "./components/list/list.model";
import { DecorationType } from "./utils/color.utils";
export namespace Components {
    interface SynthList {
        "data": Row[];
        "decimals": boolean;
        "decorationType": DecorationType;
        "enableDownload": boolean;
        "expandable": boolean;
        "fieldsConfig": FieldsConfig[];
        "filterFields": string[];
        "headerTitle": string;
        "limit": number;
        "loading": boolean;
        "update": boolean;
    }
    interface SynthListRow {
        "decorationType": DecorationType;
        "expandable": boolean;
        "fieldsConfig": FieldsConfig[];
        "i18n": any;
        "isTotal": boolean;
        "row": Row;
    }
    interface SynthNoData {
    }
}
declare global {
    interface HTMLSynthListElement extends Components.SynthList, HTMLStencilElement {
    }
    var HTMLSynthListElement: {
        prototype: HTMLSynthListElement;
        new (): HTMLSynthListElement;
    };
    interface HTMLSynthListRowElement extends Components.SynthListRow, HTMLStencilElement {
    }
    var HTMLSynthListRowElement: {
        prototype: HTMLSynthListRowElement;
        new (): HTMLSynthListRowElement;
    };
    interface HTMLSynthNoDataElement extends Components.SynthNoData, HTMLStencilElement {
    }
    var HTMLSynthNoDataElement: {
        prototype: HTMLSynthNoDataElement;
        new (): HTMLSynthNoDataElement;
    };
    interface HTMLElementTagNameMap {
        "synth-list": HTMLSynthListElement;
        "synth-list-row": HTMLSynthListRowElement;
        "synth-no-data": HTMLSynthNoDataElement;
    }
}
declare namespace LocalJSX {
    interface SynthList {
        "data"?: Row[];
        "decimals"?: boolean;
        "decorationType"?: DecorationType;
        "enableDownload"?: boolean;
        "expandable"?: boolean;
        "fieldsConfig"?: FieldsConfig[];
        "filterFields"?: string[];
        "headerTitle"?: string;
        "limit"?: number;
        "loading"?: boolean;
        "update"?: boolean;
    }
    interface SynthListRow {
        "decorationType"?: DecorationType;
        "expandable"?: boolean;
        "fieldsConfig"?: FieldsConfig[];
        "i18n"?: any;
        "isTotal"?: boolean;
        "row"?: Row;
    }
    interface SynthNoData {
    }
    interface IntrinsicElements {
        "synth-list": SynthList;
        "synth-list-row": SynthListRow;
        "synth-no-data": SynthNoData;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "synth-list": LocalJSX.SynthList & JSXBase.HTMLAttributes<HTMLSynthListElement>;
            "synth-list-row": LocalJSX.SynthListRow & JSXBase.HTMLAttributes<HTMLSynthListRowElement>;
            "synth-no-data": LocalJSX.SynthNoData & JSXBase.HTMLAttributes<HTMLSynthNoDataElement>;
        }
    }
}
