/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FilterOptionHeader, FiltersConfig, Row, SelectedFilter } from "synth-core";
import { ExpandRowEvent } from "./components/list/list.model";
export namespace Components {
    interface SynthButton {
        /**
          * Material icons id
         */
        "icon": string;
        /**
          * Button text
         */
        "text": string;
    }
    interface SynthChipsbar {
        /**
          * Filters configuration object
         */
        "filtersConfig": FiltersConfig;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
    }
    interface SynthFilter {
        /**
          * Filter description
         */
        "description": string;
        /**
          * Multiselect flag. True if filter allows multiselect toggler
         */
        "haveMultiSelect": boolean;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * This flag is true if multiselect is active
         */
        "multiSelect": boolean;
        /**
          * Filter options
         */
        "options": FilterOptionHeader[];
        /**
          * Filter plural
         */
        "plural": string;
        /**
          * Search placeholder
         */
        "searchPlaceholder": string;
        /**
          * Filter selected
         */
        "selected": SelectedFilter[];
    }
    interface SynthList {
        /**
          * Component data. Fields preffixed with `_` will not render
         */
        "data": Row[];
        /**
          * Show decimals flag
         */
        "decimals": boolean;
        /**
          * Default sorting field, it could be a private or public field
         */
        "defaultSortField": string;
        /**
          * Enable download xlsx file
         */
        "enableDownload": boolean;
        /**
          * Expandable flag
         */
        "expandable": boolean;
        /**
          * Rows that has no data on these fields will not render
         */
        "filterFields": string[];
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Rows limit. If not set will take `16` as default value or `10` in small screens
         */
        "limit": number;
        /**
          * Loading state. If true will render skeleton loader
         */
        "loading": boolean;
        /**
          * Force component update if flag is true
         */
        "update": boolean;
    }
    interface SynthListRow {
        /**
          * expand row callback
         */
        "expandHandle": (row: Row) => () => any;
        /**
          * expandable flag
         */
        "expandable": boolean;
        /**
          * Render fields
         */
        "fields": string[];
        /**
          * i18n object with translations
         */
        "i18n": any;
        /**
          * total flag
         */
        "isTotal": boolean;
        /**
          * row data
         */
        "row": Row;
    }
    interface SynthNoData {
        /**
          * Bottom text. only applies if render mode is advanced
         */
        "bottomText": string;
        /**
          * Extra i18n translation object
         */
        "i18n": { [key: string]: string };
        /**
          * Render mode [ 'simple' | 'complex' ]
         */
        "mode": string;
        /**
          * Top text only applies if render mode is advanced
         */
        "text": string;
    }
    interface SynthSkLoader {
        /**
          * Height of loader line
         */
        "height": number;
        /**
          * Number of loader lines that will be rendered
         */
        "repetitions": number;
    }
    interface SynthTitle {
        /**
          * title text
         */
        "titleText": string;
    }
    interface SynthToggler {
        /**
          * Toggler state
         */
        "active": boolean;
        /**
          * Click callback
         */
        "callback": () => any;
    }
}
declare global {
    interface HTMLSynthButtonElement extends Components.SynthButton, HTMLStencilElement {
    }
    var HTMLSynthButtonElement: {
        prototype: HTMLSynthButtonElement;
        new (): HTMLSynthButtonElement;
    };
    interface HTMLSynthChipsbarElement extends Components.SynthChipsbar, HTMLStencilElement {
    }
    var HTMLSynthChipsbarElement: {
        prototype: HTMLSynthChipsbarElement;
        new (): HTMLSynthChipsbarElement;
    };
    interface HTMLSynthFilterElement extends Components.SynthFilter, HTMLStencilElement {
    }
    var HTMLSynthFilterElement: {
        prototype: HTMLSynthFilterElement;
        new (): HTMLSynthFilterElement;
    };
    interface HTMLSynthListElement extends Components.SynthList, HTMLStencilElement {
    }
    var HTMLSynthListElement: {
        prototype: HTMLSynthListElement;
        new (): HTMLSynthListElement;
    };
    interface HTMLSynthListRowElement extends Components.SynthListRow, HTMLStencilElement {
    }
    var HTMLSynthListRowElement: {
        prototype: HTMLSynthListRowElement;
        new (): HTMLSynthListRowElement;
    };
    interface HTMLSynthNoDataElement extends Components.SynthNoData, HTMLStencilElement {
    }
    var HTMLSynthNoDataElement: {
        prototype: HTMLSynthNoDataElement;
        new (): HTMLSynthNoDataElement;
    };
    interface HTMLSynthSkLoaderElement extends Components.SynthSkLoader, HTMLStencilElement {
    }
    var HTMLSynthSkLoaderElement: {
        prototype: HTMLSynthSkLoaderElement;
        new (): HTMLSynthSkLoaderElement;
    };
    interface HTMLSynthTitleElement extends Components.SynthTitle, HTMLStencilElement {
    }
    var HTMLSynthTitleElement: {
        prototype: HTMLSynthTitleElement;
        new (): HTMLSynthTitleElement;
    };
    interface HTMLSynthTogglerElement extends Components.SynthToggler, HTMLStencilElement {
    }
    var HTMLSynthTogglerElement: {
        prototype: HTMLSynthTogglerElement;
        new (): HTMLSynthTogglerElement;
    };
    interface HTMLElementTagNameMap {
        "synth-button": HTMLSynthButtonElement;
        "synth-chipsbar": HTMLSynthChipsbarElement;
        "synth-filter": HTMLSynthFilterElement;
        "synth-list": HTMLSynthListElement;
        "synth-list-row": HTMLSynthListRowElement;
        "synth-no-data": HTMLSynthNoDataElement;
        "synth-sk-loader": HTMLSynthSkLoaderElement;
        "synth-title": HTMLSynthTitleElement;
        "synth-toggler": HTMLSynthTogglerElement;
    }
}
declare namespace LocalJSX {
    interface SynthButton {
        /**
          * Material icons id
         */
        "icon"?: string;
        /**
          * Button text
         */
        "text"?: string;
    }
    interface SynthChipsbar {
        /**
          * Filters configuration object
         */
        "filtersConfig"?: FiltersConfig;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Clear all filters event
         */
        "onClearAll"?: (event: CustomEvent<any>) => void;
        /**
          * Filter clear event
         */
        "onFilterClear"?: (event: CustomEvent<any>) => void;
        /**
          * Filter multiselect event
         */
        "onFilterMultiSelect"?: (event: CustomEvent<any>) => void;
        /**
          * Filter select event
         */
        "onFilterSelect"?: (event: CustomEvent<any>) => void;
    }
    interface SynthFilter {
        /**
          * Filter description
         */
        "description"?: string;
        /**
          * Multiselect flag. True if filter allows multiselect toggler
         */
        "haveMultiSelect"?: boolean;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * This flag is true if multiselect is active
         */
        "multiSelect"?: boolean;
        /**
          * Clear selected filters callback
         */
        "onClearEvent"?: (event: CustomEvent<any>) => void;
        /**
          * Multiselect toggler callback
         */
        "onMultiSelectEvent"?: (event: CustomEvent<any>) => void;
        /**
          * Option click event
         */
        "onOptionClickEvent"?: (event: CustomEvent<any>) => void;
        /**
          * Filter options
         */
        "options"?: FilterOptionHeader[];
        /**
          * Filter plural
         */
        "plural"?: string;
        /**
          * Search placeholder
         */
        "searchPlaceholder"?: string;
        /**
          * Filter selected
         */
        "selected"?: SelectedFilter[];
    }
    interface SynthList {
        /**
          * Component data. Fields preffixed with `_` will not render
         */
        "data"?: Row[];
        /**
          * Show decimals flag
         */
        "decimals"?: boolean;
        /**
          * Default sorting field, it could be a private or public field
         */
        "defaultSortField"?: string;
        /**
          * Enable download xlsx file
         */
        "enableDownload"?: boolean;
        /**
          * Expandable flag
         */
        "expandable"?: boolean;
        /**
          * Rows that has no data on these fields will not render
         */
        "filterFields"?: string[];
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Rows limit. If not set will take `16` as default value or `10` in small screens
         */
        "limit"?: number;
        /**
          * Loading state. If true will render skeleton loader
         */
        "loading"?: boolean;
        /**
          * Expand row event
         */
        "onExpandRow"?: (event: CustomEvent<ExpandRowEvent>) => void;
        /**
          * Force component update if flag is true
         */
        "update"?: boolean;
    }
    interface SynthListRow {
        /**
          * expand row callback
         */
        "expandHandle"?: (row: Row) => () => any;
        /**
          * expandable flag
         */
        "expandable"?: boolean;
        /**
          * Render fields
         */
        "fields"?: string[];
        /**
          * i18n object with translations
         */
        "i18n"?: any;
        /**
          * total flag
         */
        "isTotal"?: boolean;
        /**
          * row data
         */
        "row"?: Row;
    }
    interface SynthNoData {
        /**
          * Bottom text. only applies if render mode is advanced
         */
        "bottomText"?: string;
        /**
          * Extra i18n translation object
         */
        "i18n"?: { [key: string]: string };
        /**
          * Render mode [ 'simple' | 'complex' ]
         */
        "mode"?: string;
        /**
          * Top text only applies if render mode is advanced
         */
        "text"?: string;
    }
    interface SynthSkLoader {
        /**
          * Height of loader line
         */
        "height"?: number;
        /**
          * Number of loader lines that will be rendered
         */
        "repetitions"?: number;
    }
    interface SynthTitle {
        /**
          * title text
         */
        "titleText"?: string;
    }
    interface SynthToggler {
        /**
          * Toggler state
         */
        "active"?: boolean;
        /**
          * Click callback
         */
        "callback"?: () => any;
    }
    interface IntrinsicElements {
        "synth-button": SynthButton;
        "synth-chipsbar": SynthChipsbar;
        "synth-filter": SynthFilter;
        "synth-list": SynthList;
        "synth-list-row": SynthListRow;
        "synth-no-data": SynthNoData;
        "synth-sk-loader": SynthSkLoader;
        "synth-title": SynthTitle;
        "synth-toggler": SynthToggler;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "synth-button": LocalJSX.SynthButton & JSXBase.HTMLAttributes<HTMLSynthButtonElement>;
            "synth-chipsbar": LocalJSX.SynthChipsbar & JSXBase.HTMLAttributes<HTMLSynthChipsbarElement>;
            "synth-filter": LocalJSX.SynthFilter & JSXBase.HTMLAttributes<HTMLSynthFilterElement>;
            "synth-list": LocalJSX.SynthList & JSXBase.HTMLAttributes<HTMLSynthListElement>;
            "synth-list-row": LocalJSX.SynthListRow & JSXBase.HTMLAttributes<HTMLSynthListRowElement>;
            "synth-no-data": LocalJSX.SynthNoData & JSXBase.HTMLAttributes<HTMLSynthNoDataElement>;
            "synth-sk-loader": LocalJSX.SynthSkLoader & JSXBase.HTMLAttributes<HTMLSynthSkLoaderElement>;
            "synth-title": LocalJSX.SynthTitle & JSXBase.HTMLAttributes<HTMLSynthTitleElement>;
            "synth-toggler": LocalJSX.SynthToggler & JSXBase.HTMLAttributes<HTMLSynthTogglerElement>;
        }
    }
}
