/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Row } from "./components/list/list.model";
export namespace Components {
    interface SynthList {
        /**
          * Component data. Fields preffixed with `_` will not render
         */
        "data": Row[];
        /**
          * Show decimals flag
         */
        "decimals": boolean;
        /**
          * Default sorting field, it could be a private or public field
         */
        "defaultSortField": string;
        /**
          * Enable download xlsx file
         */
        "enableDownload": boolean;
        /**
          * Expandable flag
         */
        "expandable": boolean;
        /**
          * Rows that has no data on these fields will not render
         */
        "filterFields": string[];
        /**
          * Rows limit. If not set will take `16` as default value or `10` in small screens
         */
        "limit": number;
        /**
          * Loading state. If true will render skeleton loader
         */
        "loading": boolean;
        /**
          * Force component update if flag is true
         */
        "update": boolean;
    }
    interface SynthListRow {
        "expandable": boolean;
        "i18n": any;
        "isTotal": boolean;
        "row": Row;
    }
    interface SynthNoData {
        /**
          * ***optional*** Bottom text. only applies if render mode is advanced
         */
        "bottomText": string;
        /**
          * Render mode, [ 'simple' | 'complex' ]
         */
        "mode": string;
        /**
          * ***optional*** Top text. only applies if render mode is advanced
         */
        "text": string;
    }
    interface SynthTitle {
        "titleText": string;
    }
}
declare global {
    interface HTMLSynthListElement extends Components.SynthList, HTMLStencilElement {
    }
    var HTMLSynthListElement: {
        prototype: HTMLSynthListElement;
        new (): HTMLSynthListElement;
    };
    interface HTMLSynthListRowElement extends Components.SynthListRow, HTMLStencilElement {
    }
    var HTMLSynthListRowElement: {
        prototype: HTMLSynthListRowElement;
        new (): HTMLSynthListRowElement;
    };
    interface HTMLSynthNoDataElement extends Components.SynthNoData, HTMLStencilElement {
    }
    var HTMLSynthNoDataElement: {
        prototype: HTMLSynthNoDataElement;
        new (): HTMLSynthNoDataElement;
    };
    interface HTMLSynthTitleElement extends Components.SynthTitle, HTMLStencilElement {
    }
    var HTMLSynthTitleElement: {
        prototype: HTMLSynthTitleElement;
        new (): HTMLSynthTitleElement;
    };
    interface HTMLElementTagNameMap {
        "synth-list": HTMLSynthListElement;
        "synth-list-row": HTMLSynthListRowElement;
        "synth-no-data": HTMLSynthNoDataElement;
        "synth-title": HTMLSynthTitleElement;
    }
}
declare namespace LocalJSX {
    interface SynthList {
        /**
          * Component data. Fields preffixed with `_` will not render
         */
        "data"?: Row[];
        /**
          * Show decimals flag
         */
        "decimals"?: boolean;
        /**
          * Default sorting field, it could be a private or public field
         */
        "defaultSortField"?: string;
        /**
          * Enable download xlsx file
         */
        "enableDownload"?: boolean;
        /**
          * Expandable flag
         */
        "expandable"?: boolean;
        /**
          * Rows that has no data on these fields will not render
         */
        "filterFields"?: string[];
        /**
          * Rows limit. If not set will take `16` as default value or `10` in small screens
         */
        "limit"?: number;
        /**
          * Loading state. If true will render skeleton loader
         */
        "loading"?: boolean;
        /**
          * Force component update if flag is true
         */
        "update"?: boolean;
    }
    interface SynthListRow {
        "expandable"?: boolean;
        "i18n"?: any;
        "isTotal"?: boolean;
        "row"?: Row;
    }
    interface SynthNoData {
        /**
          * ***optional*** Bottom text. only applies if render mode is advanced
         */
        "bottomText"?: string;
        /**
          * Render mode, [ 'simple' | 'complex' ]
         */
        "mode"?: string;
        /**
          * ***optional*** Top text. only applies if render mode is advanced
         */
        "text"?: string;
    }
    interface SynthTitle {
        "titleText"?: string;
    }
    interface IntrinsicElements {
        "synth-list": SynthList;
        "synth-list-row": SynthListRow;
        "synth-no-data": SynthNoData;
        "synth-title": SynthTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "synth-list": LocalJSX.SynthList & JSXBase.HTMLAttributes<HTMLSynthListElement>;
            "synth-list-row": LocalJSX.SynthListRow & JSXBase.HTMLAttributes<HTMLSynthListRowElement>;
            "synth-no-data": LocalJSX.SynthNoData & JSXBase.HTMLAttributes<HTMLSynthNoDataElement>;
            "synth-title": LocalJSX.SynthTitle & JSXBase.HTMLAttributes<HTMLSynthTitleElement>;
        }
    }
}
