extends:
  - 'airbnb/hooks'
plugins:
  - 'react'
ignorePatterns:
  - '**/react-component-lib/**'
parserOptions:
  ecmaFeatures:
    jsx: true
  project: './tsconfig.json'
rules:
  no-console:
    - off
