extends:
  - 'airbnb/hooks'
plugins:
  - 'react'
ignorePatterns:
  - '**/react-component-lib/**'
parserOptions:
  ecmaFeatures:
    jsx: true
  project: './packages/glyph-react/tsconfig.json'
